// Generated by schema-bridge — do not edit by hand.
// Regenerate with `task cluster:go` (runs the schema-bridge plugin).
//
// If schema-bridge errored on a construct used here,
// the codegen needs a new mapping — extend it, don't
// hand-author this file.

package identity

type RevocationReason string

const (
	RevocationReasonEpochMismatch  RevocationReason = "epochMismatch"
	RevocationReasonUnknownKey     RevocationReason = "unknownKey"
	RevocationReasonRollbackAttack RevocationReason = "rollbackAttack"
	RevocationReasonBundleInvalid  RevocationReason = "bundleInvalid"
	RevocationReasonBundleStale    RevocationReason = "bundleStale"
)

type CertScope string

const (
	CertScopeBridgeCert      CertScope = "bridgeCert"
	CertScopeAuthorityManage CertScope = "authorityManage"
	CertScopeCertMint        CertScope = "certMint"
)

type KeyEntry struct {
	Kid       string `json:"kid"`
	PublicKey []byte `json:"publicKey"`
}

type CABundle struct {
	Epoch     uint64     `json:"epoch"`
	Seqno     uint64     `json:"seqno"`
	Keys      []KeyEntry `json:"keys"`
	KeyId     string     `json:"keyId"`
	PrevKeyId string     `json:"prevKeyId"`
	IssuedAt  int64      `json:"issuedAt"`
	Signature []byte     `json:"signature"`
}

type TokenClaims struct {
	KeyId string `json:"keyId"`
	Epoch uint64 `json:"epoch"`
}

type RevocationResult struct {
	Revoked bool             `json:"revoked"`
	Reason  RevocationReason `json:"reason"`
}

type BridgeCertResult struct {
	Certificate string    `json:"certificate"`
	PrivateKey  string    `json:"privateKey"`
	ExpiresAt   int64     `json:"expiresAt"`
	Subject     string    `json:"subject"`
	Scope       CertScope `json:"scope"`
}

type BridgeCertPair struct {
	MtlsCert    string   `json:"mtlsCert"`
	SigningCert string   `json:"signingCert"`
	Identity    string   `json:"identity"`
	Scopes      []string `json:"scopes"`
	ExpiresAt   int64    `json:"expiresAt"`
	Subject     string   `json:"subject"`
	Binding     string   `json:"binding"`
	Epoch       uint64   `json:"epoch"`
	AuthMethod  string   `json:"authMethod"`
}

type AuthorityState struct {
	Epoch uint64 `json:"epoch"`
	KeyId string `json:"keyId"`
}

type Proof struct {
	GhaOidc       *GHAClaims `json:"ghaOidc,omitempty"`
	Passkey       *[]byte    `json:"passkey,omitempty"`
	BootstrapCode *string    `json:"bootstrapCode,omitempty"`
}

type CertPairPublicKeys struct {
	Mtls    string `json:"mtls"`
	Signing string `json:"signing"`
}

type CertPairPoP struct {
	Mtls    []byte `json:"mtls"`
	Signing []byte `json:"signing"`
}

type CertPairRequest struct {
	Proof      Proof              `json:"proof"`
	PublicKeys CertPairPublicKeys `json:"publicKeys"`
	Proofs     CertPairPoP        `json:"proofs"`
}

type GHAClaims struct {
	Iss             string `json:"iss"`
	Sub             string `json:"sub"`
	Aud             string `json:"aud"`
	Exp             int64  `json:"exp"`
	Iat             int64  `json:"iat"`
	Jti             string `json:"jti"`
	Repository      string `json:"repository"`
	RepositoryOwner string `json:"repositoryOwner"`
	Ref             string `json:"ref"`
	Sha             string `json:"sha"`
	Actor           string `json:"actor"`
	Workflow        string `json:"workflow"`
	JobWorkflowRef  string `json:"jobWorkflowRef"`
	RunId           string `json:"runId"`
	EventName       string `json:"eventName"`
	Environment     string `json:"environment"`
}

type CertRequest struct {
	Scopes []CertScope `json:"scopes"`
	Proof  Proof       `json:"proof"`
}

type BeadRef struct {
	Repo        string `json:"repo"`
	BeadId      string `json:"beadId"`
	ContentHash string `json:"contentHash"`
}

type AgentIdentity struct {
	Name       string `json:"name"`
	Provider   string `json:"provider"`
	Model      string `json:"model"`
	Definition string `json:"definition"`
}

type PipelineContext struct {
	Phases       []string `json:"phases"`
	CurrentPhase uint32   `json:"currentPhase"`
	PipelineId   string   `json:"pipelineId"`
}

type DispatchPredicate struct {
	BeadRef     BeadRef          `json:"beadRef"`
	Agent       AgentIdentity    `json:"agent"`
	Pipeline    PipelineContext  `json:"pipeline"`
	SigningCert BridgeCertResult `json:"signingCert"`
	CertPair    BridgeCertPair   `json:"certPair"`
}

type HandoffPredicate struct {
	FromPhase         string           `json:"fromPhase"`
	ToPhase           string           `json:"toPhase"`
	Summary           string           `json:"summary"`
	FilesChanged      []string         `json:"filesChanged"`
	CommitShas        []string         `json:"commitShas"`
	PreviousChainHash string           `json:"previousChainHash"`
	ChainHash         string           `json:"chainHash"`
	SigningCert       BridgeCertResult `json:"signingCert"`
	CertPair          BridgeCertPair   `json:"certPair"`
}

type SignRequest struct {
	Digest    []byte `json:"digest"`
	Algorithm string `json:"algorithm"`
	Purpose   string `json:"purpose"`
}

type SignResponse struct {
	Signature []byte `json:"signature"`
	Identity  string `json:"identity"`
}

type OraclePublicKey struct {
	Key       []byte `json:"key"`
	Algorithm string `json:"algorithm"`
	CertPem   string `json:"certPem"`
	Identity  string `json:"identity"`
	ExpiresAt int64  `json:"expiresAt"`
}

type OracleInfo struct {
	Keys   []OraclePublicKey `json:"keys"`
	Scopes []string          `json:"scopes"`
	Epoch  uint64            `json:"epoch"`
}
