# cloister.capnp — AUTO-GENERATED by scripts/emit-cloister-capnp.mjs
# Per ADR-0031 (cloister-345ad1 Phase 2 + cloister-c919d7 Phase 4a).
#
# Source: cluster.toml [[routes]] + [gateway] — the operator-authored
# route list + Gateway-level surface (metadata + actor + policy).
# When [gateway] is absent / all-empty, the emitter falls through to
# the ART-default template (back-compat for pre-Phase-4a cluster.toml).
# The cluster.lock.toml [[generated_backends]] overlay is applied
# DOWNSTREAM at `task manifest` time by scripts/build-manifest.mjs;
# this file carries only the cluster.toml-declared routes.
#
# Do NOT edit by hand — your edits will be overwritten on the next emitter run.
# To regenerate: `task emit:cloister-capnp`.

@0xa1c0157e1a1f0001;
using Cloister = import "/cloister/manifest/cloister.capnp";

const gateway :Cloister.Gateway = (
  metadata = (name = "cloister-art", version = "0.1.0", metaNamespace = "art.cloister/v1"),

  actor = (
    fingerprint     = "",
    algorithm       = "ed25519",
    pubkeyBinding   = "INTERLACE_MASTER_PUBKEY",
    attestationRepo = "",
    tunnelEndpoint  = "",
  ),

  policy = (
    maxCertLifetimeSeconds = 300,
    requireInterlock       = true,
    minAlgorithm           = "ed25519",
  ),

  vaultProxyServices = [
    (
      name = "anthropic",
      upstreamBaseUrl = "https://api.anthropic.com",
      defaultAllowedSubs = [],
      rateLimitPerMinute = 120,
      injection = (headerNamed = (name = "x-api-key")),
    ),
    (
      name = "openai",
      upstreamBaseUrl = "https://api.openai.com",
      defaultAllowedSubs = [],
      rateLimitPerMinute = 120,
      injection = (authorizationBearer = void),
    )
  ],

  routes = [
    ( path = "/health", kind = (health = void) ),
    ( path = "/.well-known/interlace/index.json", kind = (wellKnownInterlace = void) ),
    ( path = "/interlace/peers/:fp", kind = (disclosure = void) ),
    ( path = "/.well-known/identity-bridge", kind = (wellKnownIdentityBridge = void) ),
    ( path = "/v2", kind = (ociRegistry = void) ),
    ( path = "/.well-known/mcp-registry", kind = (wellKnownMcpRegistry = void) ),
    ( path = "/interlace/ca-bundle", kind = (caBundle = void) ),
    ( path = "/vault/proxy",
      kind = (vaultProxy = (
        bundleIdName = "cloister-router",
      )),
    ),
    ( path = "/identity",
      kind = (serviceBindingProxy = (
        binding      = "NOTME",
        upstreamHost = "notme-bot",
        stripPrefix  = "/identity",
      )),
    ),
    ( path = "/mcp",
      kind = (mcp = (
        backends = [
          ( name          = "bead",
            handlesPrefix = "bead_",
            kind = (durableObject = (
              binding = "BEAD_STORE",
              keyArg  = "repo",
              tools   = [
                ( name = "bead_create", description = "Create a new bead (work item) in the store for the given repo.", inputSchemaJson = "" ),
                ( name = "bead_update", description = "Update fields on an existing bead.", inputSchemaJson = "" ),
                ( name = "bead_search", description = "Full-text search beads by title/description.", inputSchemaJson = "" ),
                ( name = "bead_list", description = "List beads, optionally filtered by state.", inputSchemaJson = "" ),
                ( name = "bead_close", description = "Mark a bead as done.", inputSchemaJson = "" ),
                ( name = "bead_comment", description = "Add a comment to a bead.", inputSchemaJson = "" ),
              ],
            )),
          )
        ],
      )),
    )
  ],
);
