# cloister.capnp — AUTO-GENERATED by scripts/emit-cloister-capnp.mjs
# Phase 2 of "cloister.capnp as build artifact" arc (cloister-345ad1, ADR-0031).
#
# Source: cluster.toml [[routes]] — the operator-authored route list.
# gateway.metadata + actor + policy stay pinned to ART-default values
# until Phase 3 lands a `[gateway]` operator surface in cluster.toml.
# The cluster.lock.toml [[generated_backends]] overlay is applied
# DOWNSTREAM at `task manifest` time by scripts/build-manifest.mjs;
# this file carries only the cluster.toml-declared routes.
#
# Do NOT edit by hand — your edits will be overwritten on the next emitter run.
# To regenerate: `task emit:cloister-capnp`.

@0xa1c0157e1a1f0001;
using Cloister = import "/cloister/manifest/cloister.capnp";

const gateway :Cloister.Gateway = (
  metadata = (name = "cloister-art", version = "0.1.0"),

  actor = (
    fingerprint     = "sha256:placeholder-pinned-at-deploy-time",
    algorithm       = "ed25519",
    pubkeyBinding   = "INTERLACE_MASTER_PUBKEY",
    attestationRepo = "",
    tunnelEndpoint  = "",
  ),

  policy = (
    maxCertLifetimeSeconds = 300,
    requireInterlock       = true,
    minAlgorithm           = "ed25519",
  ),

  routes = [
    ( path = "/health", kind = (health = void) ),
    ( path = "/.well-known/interlace/index.json", kind = (wellKnownInterlace = void) ),
    ( path = "/interlace/peers/:fp", kind = (disclosure = void) ),
    ( path = "/.well-known/identity-bridge", kind = (wellKnownIdentityBridge = void) ),
    ( path = "/v2", kind = (ociRegistry = void) ),
    ( path = "/.well-known/mcp-registry", kind = (wellKnownMcpRegistry = void) ),
    ( path = "/interlace/ca-bundle", kind = (caBundle = void) ),
    ( path = "/identity",
      kind = (serviceBindingProxy = (
        binding      = "NOTME",
        upstreamHost = "notme-bot",
        stripPrefix  = "/identity",
      )),
    ),
    ( path = "/mcp",
      kind = (mcp = (
        backends = [
          ( name          = "bead",
            handlesPrefix = "bead_",
            kind = (durableObject = (
              binding = "BEAD_STORE",
              keyArg  = "repo",
              tools   = [
                ( name = "bead_create", description = "Create a new bead (work item) in the store for the given repo.", inputSchemaJson = "" ),
                ( name = "bead_update", description = "Update fields on an existing bead.", inputSchemaJson = "" ),
                ( name = "bead_search", description = "Full-text search beads by title/description.", inputSchemaJson = "" ),
                ( name = "bead_list", description = "List beads, optionally filtered by state.", inputSchemaJson = "" ),
                ( name = "bead_close", description = "Mark a bead as done.", inputSchemaJson = "" ),
                ( name = "bead_comment", description = "Add a comment to a bead.", inputSchemaJson = "" ),
              ],
            )),
          ),
          ( name          = "mache",
            handlesPrefix = "mache_",
            kind = (mcpProxy = (
              urlBinding      = "MACHE_MCP_URL",
              serviceBinding  = "MACHE_MCP",
              tools           = [],
              dynamicTools    = true,
              stripPrefix     = "mache_",
              requiresSession = true,
            )),
          )
        ],
      )),
    )
  ],
);
