/// <reference types="@cloudflare/vitest-pool-workers/types" />
//
// RECEIPTS.md §7.1 conformance — the cross-implementation pin for
// `canonicalCbor(commitmentCborMap(...))` (cloister-35ccf7).
//
// ── Why this file exists, in the vector's own words ──────────────────────────
//
// "Pinning the INPUTS (not only the output bytes) is the point: if either
//  side's commitment shape changes — a field added, order moved, an integer
//  head widened — the side that made the change fails its own suite, instead
//  of the other side failing at integration. A one-sided pin lets the party
//  who can break the contract be the only one who cannot detect breaking it."
//
// Cloister previously pinned only the ENCODER'S PRIMITIVES
// (test/wire/receipts-cbor.test.ts — `canonicalCbor({x: 0x100000000})` and
// friends). Nothing pinned a composed commitment, so a change to
// commitmentCborMap's shape stayed green here and failed on notme's side.
// This is that mirror.
//
// ── Provenance, which is the unusual part ────────────────────────────────────
//
// The vector was not authored by either implementation asserting its own
// output is canonical. Each case was generated by encoding `input` with BOTH
// cloister's `canonicalCbor(commitmentCborMap(...))` AND notme's
// `encodeCanonicalMap(...)`, and requiring byte-for-byte agreement per case —
// 12 cases, 0 disagreements — before either side pinned it.
//
// That distinction is load-bearing. The defect this vector exists to prevent
// survived 17 green tests on notme's side precisely because those fixtures had
// been built WITH the encoder under test: a fixed point that any
// self-consistent encoder satisfies, including a wrong one. Cloister's encoder
// being independently correct is the only reason it surfaced before
// production.
//
// ── The landmines it deliberately covers ─────────────────────────────────────
//
//   - timestamp_ms at every CBOR integer-head boundary (23/24, 255/256,
//     65535/65536, 2^32-1/2^32) — exactly where cbor-x promoted to float64,
//     which is where the defect lived
//   - body_hash whose first byte has the high bit set (0xff)
//   - headers_hash = SHA-256 of the canonical empty map (0xa0)
//   - status at the 2xx upper bound (299)

import { describe, expect, it } from "vitest";
import vectors from "../../interlace-spec/0.2.0-draft/test-vectors/receipt-canonical-bytes.json";
import { canonicalCbor } from "../../src/wire/receipts-cbor";
import { commitmentCborMap, type ReceiptCommitment } from "../../src/wire/receipts";

const hexToBytes = (h: string): Uint8Array =>
  new Uint8Array((h.match(/../g) ?? []).map((byte: string) => parseInt(byte, 16)));

const bytesToHex = (b: Uint8Array): string =>
  [...b].map((x) => x.toString(16).padStart(2, "0")).join("");

/**
 * Build a ReceiptCommitment from the vector's hex-encoded input shape.
 *
 * NOT cast with `as ReceiptCommitment`. The first draft was, and it silently
 * dropped `epoch` — all 12 cases failed with a 7-key map (`a7`) against the
 * pinned 8-key one (`a8`), which reads like an encoder disagreement rather
 * than a missing field. An exact return type makes the compiler name the
 * omission instead, which is the whole argument this vector is making one
 * level up: a fixture built loosely enough to accept your own mistake tests
 * nothing.
 */
function commitmentFrom(input: Record<string, unknown>): ReceiptCommitment {
  return {
    nonce:       hexToBytes(input.nonce_hex as string),
    requestHash: hexToBytes(input.request_hash_hex as string),
    status:      input.status as number,
    bodyHash:    hexToBytes(input.body_hash_hex as string),
    headersHash: hexToBytes(input.headers_hash_hex as string),
    timestampMs: input.timestamp_ms as number,
    actorFp:     hexToBytes(input.actor_fp_hex as string),
    epoch:       input.epoch as number,
  };
}

describe("RECEIPTS.md §7.1 — receipt-canonical-bytes vectors", () => {
  it("carries the cases this suite claims to drive", () => {
    // Guards against passing vacuously: every assertion below is a no-op over
    // an empty array, and a spec-mandated vector is exactly the kind of file
    // that gets moved or truncated.
    expect(vectors.vectors.length).toBe(12);
    expect(vectors.landmines_covered.length).toBeGreaterThanOrEqual(4);
  });

  for (const c of vectors.vectors) {
    it(`${c.name} encodes to the pinned bytes`, () => {
      const out = canonicalCbor(commitmentCborMap(commitmentFrom(c.input)));
      // Compare hex rather than byte arrays so a failure prints the diverging
      // sequence, not "Uint8Array(243) !== Uint8Array(243)".
      expect(bytesToHex(out)).toBe(c.expected_canonical_cbor_hex);
      expect(out.byteLength).toBe(c.byte_length);
    });
  }
});

describe("the integer-head boundaries the defect lived at", () => {
  // Called out separately because these are the cases that matter: an encoder
  // that promotes a shortest-form uint to float64 passes a baseline vector and
  // fails only here.
  const boundaries = vectors.vectors.filter((c) => c.name.startsWith("timestamp_"));

  it("covers every CBOR uint head width", () => {
    expect(boundaries.length).toBeGreaterThanOrEqual(8);
  });

  it.each(boundaries.map((c) => [c.name, c] as const))(
    "%s uses a canonical (shortest-form) integer head",
    (_name, c) => {
      const out = canonicalCbor(commitmentCborMap(commitmentFrom(c.input)));
      expect(bytesToHex(out)).toBe(c.expected_canonical_cbor_hex);
      // No float64 heads (0xfb) anywhere in a conformant commitment — that is
      // the specific corruption cbor-x introduced.
      expect(bytesToHex(out)).not.toMatch(/fb[0-9a-f]{16}/);
    },
  );
});
