// IR → zod TypeScript source.
//
// Emits one zod schema per struct plus a TypeScript type alias derived
// from it. Struct-to-struct references resolve by name; topological
// order is enforced via forward-declaration via `z.lazy(...)`.

use std::fmt::Write as _;

use crate::error::Result;
use crate::ir::{FieldType, ScalarType, Schema, Struct, StructField};

pub fn emit(schema: &Schema) -> Result<String> {
    let mut out = String::new();
    writeln!(out, "// Generated by schema-bridge — do not edit by hand.").unwrap();
    writeln!(
        out,
        "// Regenerate with `task manifest` (runs the schema-bridge plugin)."
    )
    .unwrap();
    writeln!(out, "//").unwrap();
    writeln!(out, "// If schema-bridge errored on a construct used here,").unwrap();
    writeln!(out, "// the codegen needs a new mapping — extend it, don't").unwrap();
    writeln!(out, "// hand-author this file.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, r#"import {{ z }} from "zod";"#).unwrap();
    writeln!(out).unwrap();

    for s in &schema.structs {
        emit_struct(&mut out, s)?;
        writeln!(out).unwrap();
    }

    Ok(out)
}

fn emit_struct(out: &mut String, s: &Struct) -> Result<()> {
    // `z.lazy` lets struct refs forward-declare without a topological
    // sort. The cost is one extra closure per schema; the saving is
    // not having to detect cycles.
    writeln!(
        out,
        "export const {name}Schema: z.ZodType<{name}> = z.lazy(() => z.object({{",
        name = s.name
    )
    .unwrap();
    for field in &s.fields {
        let rendered = render_field(field);
        writeln!(out, "  {}: {},", field.name, rendered).unwrap();
    }
    writeln!(out, "}}));").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "export interface {} {{", s.name).unwrap();
    for field in &s.fields {
        let ts_ty = render_ts_type(&field.ty);
        writeln!(out, "  {}: {};", field.name, ts_ty).unwrap();
    }
    writeln!(out, "}}").unwrap();

    Ok(())
}

fn render_field(field: &StructField) -> String {
    match &field.ty {
        FieldType::Scalar(s) => render_zod_scalar(*s).to_owned(),
        FieldType::StructRef(name) => format!("{name}Schema"),
    }
}

fn render_zod_scalar(s: ScalarType) -> &'static str {
    match s {
        ScalarType::Void => "z.void()",
        ScalarType::Bool => "z.boolean()",
        ScalarType::Int8
        | ScalarType::Int16
        | ScalarType::Int32
        | ScalarType::Int64 => "z.number().int()",
        ScalarType::UInt8
        | ScalarType::UInt16
        | ScalarType::UInt32
        | ScalarType::UInt64 => "z.number().int().nonnegative()",
        ScalarType::Float32 | ScalarType::Float64 => "z.number()",
        ScalarType::Text => "z.string()",
        ScalarType::Data => "z.instanceof(Uint8Array)",
    }
}

fn render_ts_type(t: &FieldType) -> String {
    match t {
        FieldType::Scalar(s) => render_ts_scalar(*s).to_owned(),
        FieldType::StructRef(name) => name.clone(),
    }
}

fn render_ts_scalar(s: ScalarType) -> &'static str {
    match s {
        ScalarType::Void => "void",
        ScalarType::Bool => "boolean",
        ScalarType::Int8
        | ScalarType::Int16
        | ScalarType::Int32
        | ScalarType::Int64
        | ScalarType::UInt8
        | ScalarType::UInt16
        | ScalarType::UInt32
        | ScalarType::UInt64
        | ScalarType::Float32
        | ScalarType::Float64 => "number",
        ScalarType::Text => "string",
        ScalarType::Data => "Uint8Array",
    }
}
