// SPDX-License-Identifier: AGPL-3.0-or-later
// Local development bootstrap per ADR-0014 v2.

import { createHash, randomBytes } from "node:crypto";
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const DEV_KEK_VAR = "DEV_VAULT_KEK";
const KEK_SOURCE_VAR = "VAULT_KEK_SOURCE";
const KEK_SOURCE_VAL = `env://${DEV_KEK_VAR}`;
const PUBKEY_VAR = "INTERLACE_ROOT_PUBKEY";
const ACTOR_FP_VAR = "INTERLACE_ACTOR_FP";

/**
 * Derive `sha256:<hex>` over the raw master public key.
 *
 * Same derivation the runtime validates (src/routes/actor-fingerprint.ts), and
 * imported from nowhere on purpose — this file is plain Node and that one is a
 * Worker module. The SHAPE is pinned on both sides instead: a rail asserts the
 * two agree, because two derivations of one digest is exactly how a published
 * fingerprint and its real key drift apart.
 */
function fingerprintFromPubkeyB64(pubkeyB64) {
  const raw = Buffer.from(pubkeyB64, "base64");
  if (raw.length === 0) return null;
  return `sha256:${createHash("sha256").update(raw).digest("hex")}`;
}

export function parseEnv(content) {
  const entries = new Map();
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq < 0) continue;
    const name = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    if (name) entries.set(name, value);
  }
  return entries;
}

export function serializeEnv(entries, header) {
  const lines = header ? [header, ""] : [];
  for (const [name, value] of entries) lines.push(`${name}=${value}`);
  lines.push("");
  return lines.join("\n");
}

async function fetchNotmePubkey(url, fetchImpl) {
  if (!url) return { ok: false, reason: "notme-disabled", detail: "NOTME_DEV_URL empty" };
  let response;
  try {
    response = await fetchImpl(`${url}/internal/ca-bundle`);
  } catch (error) {
    return { ok: false, reason: "notme-not-running", detail: String(error?.message ?? error) };
  }
  if (!response.ok) return { ok: false, reason: "notme-http", detail: `HTTP ${response.status}` };
  let bundle;
  try {
    bundle = await response.json();
  } catch (error) {
    return { ok: false, reason: "notme-bad-json", detail: String(error?.message ?? error) };
  }
  const key = bundle?.keys?.[bundle.keyId];
  return typeof key === "string" && key
    ? { ok: true, pubkey: key }
    : { ok: false, reason: "notme-shape", detail: "bundle has no keys[keyId]" };
}

function fetchSignetPubkey({ env, spawn }) {
  const signet = env.SIGNET_BIN || "signet";
  const authorityUrl = env.SIGNET_AUTHORITY_URL || "";
  const args = ["authority", "pubkey"];
  if (authorityUrl) args.push("--url", authorityUrl);
  const result = spawn(signet, args, {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
  if (result.error) return { ok: false, reason: "signet-not-found", detail: String(result.error) };
  if (result.status !== 0) {
    return { ok: false, reason: "signet-error", detail: (result.stderr || "").trim() };
  }
  const pubkey = (result.stdout || "").trim();
  return pubkey
    ? { ok: true, pubkey }
    : { ok: false, reason: "signet-empty", detail: "stdout was empty" };
}

/** Create or refresh the gitignored local development environment. */
export async function bootstrapLocalDev({
  root = process.cwd(),
  env = process.env,
  fetchImpl = globalThis.fetch,
  spawn = spawnSync,
  exists = existsSync,
  read = readFileSync,
  write = writeFileSync,
  random = randomBytes,
  log = console.log,
} = {}) {
  const envLocal = resolve(root, ".env.local");
  const entries = parseEnv(exists(envLocal) ? read(envLocal, "utf8") : "");
  const header = [
    "# .env.local — generated by `cloister dev bootstrap` per ADR-0014 v2.",
    "# DO NOT COMMIT. Gitignored. Per-user dev secrets only.",
    "#",
    "# Re-run `cloister dev bootstrap` to regenerate. To wipe, delete this file.",
  ].join("\n");

  let generated = false;
  if (!entries.get(DEV_KEK_VAR)) {
    entries.set(DEV_KEK_VAR, random(32).toString("hex"));
    generated = true;
  }
  const sourceWas = entries.get(KEK_SOURCE_VAR);
  entries.set(KEK_SOURCE_VAR, KEK_SOURCE_VAL);

  const pubkeyWas = entries.get(PUBKEY_VAR);
  let pubkeyOutcome = { kind: "kept" };
  if (env.INTERLACE_PUBKEY_REFRESH || !pubkeyWas) {
    const notmeUrl = env.NOTME_DEV_URL ?? "http://localhost:8788";
    let fetched = await fetchNotmePubkey(notmeUrl, fetchImpl);
    let via = `local notme (${notmeUrl})`;
    let notmeReason;
    if (!fetched.ok) {
      notmeReason = fetched.reason;
      fetched = fetchSignetPubkey({ env, spawn });
      via = env.SIGNET_AUTHORITY_URL || "local keystore (signet)";
    }
    pubkeyOutcome = fetched.ok
      ? { kind: pubkeyWas ? "refreshed" : "fetched", via }
      : { kind: "skipped", reason: fetched.reason, detail: fetched.detail, notmeReason };
    if (fetched.ok) entries.set(PUBKEY_VAR, fetched.pubkey);
  }

  // The identity surfaces gate on a fingerprint, not on the pubkey — and it is
  // DERIVABLE from the pubkey, so leaving it unset produced a scaffold that
  // declared `wellKnownIdentityBridge` and answered 404 on all five of its
  // paths. Deriving it here is what makes `cloister dev bootstrap` produce a
  // LIVE surface rather than a declared-but-dead one.
  //
  // Keyed off the pubkey actually in the file (not just a fresh fetch), so a
  // tree bootstrapped before this existed gains the fingerprint on the next run
  // without needing INTERLACE_PUBKEY_REFRESH.
  let actorFpOutcome = { kind: "skipped", reason: "no-pubkey" };
  const pubkeyNow = entries.get(PUBKEY_VAR);
  if (pubkeyNow) {
    const derived = fingerprintFromPubkeyB64(pubkeyNow);
    if (!derived) {
      actorFpOutcome = { kind: "skipped", reason: "pubkey-undecodable" };
    } else if (entries.get(ACTOR_FP_VAR) === derived) {
      actorFpOutcome = { kind: "kept", value: derived };
    } else {
      // Overwritten rather than preserved when it disagrees: a fingerprint that
      // does not match the pubkey in the same file is worse than none, because
      // it publishes a `kid` no verifier can resolve while looking configured.
      const had = entries.get(ACTOR_FP_VAR);
      entries.set(ACTOR_FP_VAR, derived);
      actorFpOutcome = { kind: had ? "corrected" : "derived", value: derived };
    }
  }

  write(envLocal, serializeEnv(entries, header), { mode: 0o600 });

  log("cloister dev bootstrap:");
  log(`  ${envLocal}`);
  log(generated
    ? `  ✓ Generated ${DEV_KEK_VAR} (32 bytes, hex)`
    : `  → Reusing existing ${DEV_KEK_VAR}`);
  log(sourceWas !== KEK_SOURCE_VAL
    ? `  ✓ Set ${KEK_SOURCE_VAR}=${KEK_SOURCE_VAL}`
    : `  → ${KEK_SOURCE_VAR} already set correctly`);
  if (pubkeyOutcome.kind === "fetched") {
    log(`  ✓ Set ${PUBKEY_VAR} from ${pubkeyOutcome.via} (lease gate ON)`);
  } else if (pubkeyOutcome.kind === "refreshed") {
    log(`  ✓ Refreshed ${PUBKEY_VAR} from ${pubkeyOutcome.via}`);
  } else if (pubkeyOutcome.kind === "kept") {
    log(`  → ${PUBKEY_VAR} already set — kept (set INTERLACE_PUBKEY_REFRESH=1 to re-fetch)`);
  } else {
    log(
      `  → ${PUBKEY_VAR} unset — no authority key available ` +
      `(notme: ${pubkeyOutcome.notmeReason ?? "n/a"}, signet: ${pubkeyOutcome.reason}). ` +
      "Lease gate OFF (dev mode).",
    );
    log(`       set CLOISTER_WORKER_DIR_NOTME_BOT=<path to notme/worker> and re-run —`);
    log("       `cloister run` starts every Worker wrangler.toml binds, so notme no");
    log("       longer needs starting by hand. Or install signet, or set");
    log("       INTERLACE_ROOT_PUBKEY=<base64> in .env.local directly.");
    if (pubkeyOutcome.detail) log(`       signet detail: ${pubkeyOutcome.detail.split("\n")[0]}`);
  }
  if (actorFpOutcome.kind === "derived") {
    log(`  ✓ Derived ${ACTOR_FP_VAR}=${actorFpOutcome.value} (identity surfaces ON)`);
  } else if (actorFpOutcome.kind === "corrected") {
    log(`  ✓ Corrected ${ACTOR_FP_VAR} — it disagreed with ${PUBKEY_VAR}`);
  } else if (actorFpOutcome.kind === "kept") {
    log(`  → ${ACTOR_FP_VAR} already matches ${PUBKEY_VAR}`);
  } else {
    log(`  → ${ACTOR_FP_VAR} unset (${actorFpOutcome.reason}) — identity surfaces 404.`);
  }
  log("");
  log("Next:");
  log("  cloister dev serve   # local Worker on :8787");
  log("  task lint             # full test gate");
  return { envLocal, generated, pubkeyOutcome, actorFpOutcome };
}

export async function main(_argv = [], deps = {}) {
  await bootstrapLocalDev(deps);
  return 0;
}
