// Code generated by capnpc-go. DO NOT EDIT.

package wire

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	strconv "strconv"
)

type Manifest capnp.Struct

// Manifest_TypeID is the unique identifier for the type Manifest.
const Manifest_TypeID = 0x85c13b5006b2e242

func NewManifest(s *capnp.Segment) (Manifest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return Manifest(st), err
}

func NewRootManifest(s *capnp.Segment) (Manifest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return Manifest(st), err
}

func ReadRootManifest(msg *capnp.Message) (Manifest, error) {
	root, err := msg.Root()
	return Manifest(root.Struct()), err
}

func (s Manifest) String() string {
	str, _ := text.Marshal(0x85c13b5006b2e242, capnp.Struct(s))
	return str
}

func (s Manifest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Manifest) DecodeFromPtr(p capnp.Ptr) Manifest {
	return Manifest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Manifest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Manifest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Manifest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Manifest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Manifest) Sequence() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Manifest) SetSequence(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Manifest) PublicKey() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Manifest) HasPublicKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Manifest) SetPublicKey(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s Manifest) Signature() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s Manifest) HasSignature() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Manifest) SetSignature(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

func (s Manifest) ContentHash() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return []byte(p.Data()), err
}

func (s Manifest) HasContentHash() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Manifest) SetContentHash(v []byte) error {
	return capnp.Struct(s).SetData(2, v)
}

// Manifest_List is a list of Manifest.
type Manifest_List = capnp.StructList[Manifest]

// NewManifest creates a new list of Manifest.
func NewManifest_List(s *capnp.Segment, sz int32) (Manifest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[Manifest](l), err
}

// Manifest_Future is a wrapper for a Manifest promised by a client call.
type Manifest_Future struct{ *capnp.Future }

func (f Manifest_Future) Struct() (Manifest, error) {
	p, err := f.Future.Ptr()
	return Manifest(p.Struct()), err
}

type ToolCall capnp.Struct

// ToolCall_TypeID is the unique identifier for the type ToolCall.
const ToolCall_TypeID = 0x996d5ba767819739

func NewToolCall(s *capnp.Segment) (ToolCall, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return ToolCall(st), err
}

func NewRootToolCall(s *capnp.Segment) (ToolCall, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return ToolCall(st), err
}

func ReadRootToolCall(msg *capnp.Message) (ToolCall, error) {
	root, err := msg.Root()
	return ToolCall(root.Struct()), err
}

func (s ToolCall) String() string {
	str, _ := text.Marshal(0x996d5ba767819739, capnp.Struct(s))
	return str
}

func (s ToolCall) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ToolCall) DecodeFromPtr(p capnp.Ptr) ToolCall {
	return ToolCall(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ToolCall) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ToolCall) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ToolCall) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ToolCall) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ToolCall) UpstreamId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ToolCall) HasUpstreamId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ToolCall) UpstreamIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ToolCall) SetUpstreamId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ToolCall) ToolName() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ToolCall) HasToolName() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ToolCall) ToolNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ToolCall) SetToolName(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ToolCall) ArgumentsJson() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return []byte(p.Data()), err
}

func (s ToolCall) HasArgumentsJson() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ToolCall) SetArgumentsJson(v []byte) error {
	return capnp.Struct(s).SetData(2, v)
}

// ToolCall_List is a list of ToolCall.
type ToolCall_List = capnp.StructList[ToolCall]

// NewToolCall creates a new list of ToolCall.
func NewToolCall_List(s *capnp.Segment, sz int32) (ToolCall_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return capnp.StructList[ToolCall](l), err
}

// ToolCall_Future is a wrapper for a ToolCall promised by a client call.
type ToolCall_Future struct{ *capnp.Future }

func (f ToolCall_Future) Struct() (ToolCall, error) {
	p, err := f.Future.Ptr()
	return ToolCall(p.Struct()), err
}

type ToolResult capnp.Struct

// ToolResult_TypeID is the unique identifier for the type ToolResult.
const ToolResult_TypeID = 0x881f943cd35fcd99

func NewToolResult(s *capnp.Segment) (ToolResult, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return ToolResult(st), err
}

func NewRootToolResult(s *capnp.Segment) (ToolResult, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return ToolResult(st), err
}

func ReadRootToolResult(msg *capnp.Message) (ToolResult, error) {
	root, err := msg.Root()
	return ToolResult(root.Struct()), err
}

func (s ToolResult) String() string {
	str, _ := text.Marshal(0x881f943cd35fcd99, capnp.Struct(s))
	return str
}

func (s ToolResult) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ToolResult) DecodeFromPtr(p capnp.Ptr) ToolResult {
	return ToolResult(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ToolResult) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ToolResult) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ToolResult) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ToolResult) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ToolResult) Content() (Content_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Content_List(p.List()), err
}

func (s ToolResult) HasContent() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ToolResult) SetContent(v Content_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewContent sets the content field to a newly
// allocated Content_List, preferring placement in s's segment.
func (s ToolResult) NewContent(n int32) (Content_List, error) {
	l, err := NewContent_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Content_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s ToolResult) IsError() bool {
	return capnp.Struct(s).Bit(0)
}

func (s ToolResult) SetIsError(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

// ToolResult_List is a list of ToolResult.
type ToolResult_List = capnp.StructList[ToolResult]

// NewToolResult creates a new list of ToolResult.
func NewToolResult_List(s *capnp.Segment, sz int32) (ToolResult_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[ToolResult](l), err
}

// ToolResult_Future is a wrapper for a ToolResult promised by a client call.
type ToolResult_Future struct{ *capnp.Future }

func (f ToolResult_Future) Struct() (ToolResult, error) {
	p, err := f.Future.Ptr()
	return ToolResult(p.Struct()), err
}

type Content capnp.Struct
type Content_body Content
type Content_body_Which uint16

const (
	Content_body_Which_text     Content_body_Which = 0
	Content_body_Which_binary   Content_body_Which = 1
	Content_body_Which_resource Content_body_Which = 2
)

func (w Content_body_Which) String() string {
	const s = "textbinaryresource"
	switch w {
	case Content_body_Which_text:
		return s[0:4]
	case Content_body_Which_binary:
		return s[4:10]
	case Content_body_Which_resource:
		return s[10:18]

	}
	return "Content_body_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Content_TypeID is the unique identifier for the type Content.
const Content_TypeID = 0xa84e63fd0cceabc1

func NewContent(s *capnp.Segment) (Content, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Content(st), err
}

func NewRootContent(s *capnp.Segment) (Content, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Content(st), err
}

func ReadRootContent(msg *capnp.Message) (Content, error) {
	root, err := msg.Root()
	return Content(root.Struct()), err
}

func (s Content) String() string {
	str, _ := text.Marshal(0xa84e63fd0cceabc1, capnp.Struct(s))
	return str
}

func (s Content) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Content) DecodeFromPtr(p capnp.Ptr) Content {
	return Content(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Content) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Content) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Content) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Content) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Content) Body() Content_body { return Content_body(s) }

func (s Content_body) Which() Content_body_Which {
	return Content_body_Which(capnp.Struct(s).Uint16(0))
}
func (s Content_body) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Content_body) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Content_body) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Content_body) Text() (string, error) {
	if capnp.Struct(s).Uint16(0) != 0 {
		panic("Which() != text")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Content_body) HasText() bool {
	if capnp.Struct(s).Uint16(0) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Content_body) TextBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Content_body) SetText(v string) error {
	capnp.Struct(s).SetUint16(0, 0)
	return capnp.Struct(s).SetText(0, v)
}

func (s Content_body) Binary() (BinaryContent, error) {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != binary")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return BinaryContent(p.Struct()), err
}

func (s Content_body) HasBinary() bool {
	if capnp.Struct(s).Uint16(0) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Content_body) SetBinary(v BinaryContent) error {
	capnp.Struct(s).SetUint16(0, 1)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewBinary sets the binary field to a newly
// allocated BinaryContent struct, preferring placement in s's segment.
func (s Content_body) NewBinary() (BinaryContent, error) {
	capnp.Struct(s).SetUint16(0, 1)
	ss, err := NewBinaryContent(capnp.Struct(s).Segment())
	if err != nil {
		return BinaryContent{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Content_body) Resource() ([]byte, error) {
	if capnp.Struct(s).Uint16(0) != 2 {
		panic("Which() != resource")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Content_body) HasResource() bool {
	if capnp.Struct(s).Uint16(0) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Content_body) SetResource(v []byte) error {
	capnp.Struct(s).SetUint16(0, 2)
	return capnp.Struct(s).SetData(0, v)
}

// Content_List is a list of Content.
type Content_List = capnp.StructList[Content]

// NewContent creates a new list of Content.
func NewContent_List(s *capnp.Segment, sz int32) (Content_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Content](l), err
}

// Content_Future is a wrapper for a Content promised by a client call.
type Content_Future struct{ *capnp.Future }

func (f Content_Future) Struct() (Content, error) {
	p, err := f.Future.Ptr()
	return Content(p.Struct()), err
}
func (p Content_Future) Body() Content_body_Future { return Content_body_Future{p.Future} }

// Content_body_Future is a wrapper for a Content_body promised by a client call.
type Content_body_Future struct{ *capnp.Future }

func (f Content_body_Future) Struct() (Content_body, error) {
	p, err := f.Future.Ptr()
	return Content_body(p.Struct()), err
}
func (p Content_body_Future) Binary() BinaryContent_Future {
	return BinaryContent_Future{Future: p.Future.Field(0, nil)}
}

type BinaryContent capnp.Struct

// BinaryContent_TypeID is the unique identifier for the type BinaryContent.
const BinaryContent_TypeID = 0xe004d79355ac5adb

func NewBinaryContent(s *capnp.Segment) (BinaryContent, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return BinaryContent(st), err
}

func NewRootBinaryContent(s *capnp.Segment) (BinaryContent, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return BinaryContent(st), err
}

func ReadRootBinaryContent(msg *capnp.Message) (BinaryContent, error) {
	root, err := msg.Root()
	return BinaryContent(root.Struct()), err
}

func (s BinaryContent) String() string {
	str, _ := text.Marshal(0xe004d79355ac5adb, capnp.Struct(s))
	return str
}

func (s BinaryContent) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (BinaryContent) DecodeFromPtr(p capnp.Ptr) BinaryContent {
	return BinaryContent(capnp.Struct{}.DecodeFromPtr(p))
}

func (s BinaryContent) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s BinaryContent) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s BinaryContent) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s BinaryContent) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s BinaryContent) Data() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s BinaryContent) HasData() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s BinaryContent) SetData(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s BinaryContent) MimeType() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s BinaryContent) HasMimeType() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s BinaryContent) MimeTypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s BinaryContent) SetMimeType(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// BinaryContent_List is a list of BinaryContent.
type BinaryContent_List = capnp.StructList[BinaryContent]

// NewBinaryContent creates a new list of BinaryContent.
func NewBinaryContent_List(s *capnp.Segment, sz int32) (BinaryContent_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[BinaryContent](l), err
}

// BinaryContent_Future is a wrapper for a BinaryContent promised by a client call.
type BinaryContent_Future struct{ *capnp.Future }

func (f BinaryContent_Future) Struct() (BinaryContent, error) {
	p, err := f.Future.Ptr()
	return BinaryContent(p.Struct()), err
}

const schema_a1c0157e2a1e0001 = "x\xdat\x92OL\x13[\x14\xc6\xcfw\xef@\x1fI" +
	"\xfb\xda\xc9\xf0\xf2v\x8f\xcd[h#\x04w\x88\x1aH" +
	"\x0bQ\x10H/\xa1\x89\xe2B\xa6\xed\x08\x93Lg\xca" +
	"\xcc4\xd0h$&\x9a\xe8\xd2\xa81,Y\x10%J" +
	"\x8c\xeet%\xecu\xa1\x0b\x17n\x0c.L\xdc\xbb\xac" +
	"\xd7\xdc\x0e\xfd\x03\xc8\xee\xe4\xcb\xbd\xe7|\xbf\xef\x9c\xc1" +
	"\x1b\x18\xd5N'V81q\xa2\xab[f\xf6^w" +
	"\xe7\xce\xee\xdc%\x91\x04\xea\xf8/}\xeb\x9fw\x1b]" +
	"<Fdl`\xd7\xd8\x82\xaa6\xf1\x9d \xd7\xdf_" +
	"\xfbt\xeeQ\xdf\xbd\x83O\x1b\x0f\xee\xb3\x8f\xc6c\xa6" +
	"\xaa\x07l\x85 \xcf<\xb9\xbd\xf8\xf4jy\x9d\xf4\xe4" +
	"\xa1\xa6u\xb6kD\x15\xf8K\x82\xdcy\xfe!^/" +
	"\xce<\xfbC\xd3M\xfe\xd6\xd8n<\xdd\xe2#\x04\xa9" +
	"_\xf8\xf9\xcd\xc9l\xbc!\xf1/:>\xe6\x11\x03'" +
	"2\xb6\xf9\x1e\xc1x\xd5\xe8\xfae\xfeE\xfe\xe1g\xed" +
	"\xeb\x81\xf9\x0d\x7f\xd3\xda\x0f\xe3\x8a\xa6\xaa\xbc\xb6B\xfd" +
	"\xb2\xe8xv\x10Z>\x1b(\x9a\x15\xb72<m\xba" +
	"\xf6u+\x08)\x07\x88\x14\xd7\x884\x10\xe9\xe6$\x91" +
	"X\xe0\x10\x0e\x03\xd0\x0b\xa5\xd9\xb3Db\x89C\x84\x0c" +
	":C/\x18\x91\xbe\xac\xc4\x0a\x87\xb8\xc9\xa0s\xd6\xab" +
	"\xac\xe9\xb5\x02\x91X\xe5\x10w\x18d`-W-\xb7" +
	"h\x11\x11z\x88\xa1\x87 +\xd5\x82c\x17/Y\x84" +
	"\x1a\x12\xc4\x90 \xc8\xc0^t\xcd\xb0\xea\x13\xac\x96V" +
	"\xf4\xdc\xd0r\xc3\x8b\x143\x83\xa5\xb6z\x88a\xce\xf3" +
	"\x9cY+\xa8:\x08\x15\xc5_-\x8a\x93\x19\"\xf1?" +
	"\x87\x18mS\x9cW\xda\x10\x87\x18cX\xdb\xef\x8f\xbf" +
	"\x099\x0e\xa4\xda)\x13\x94\xb8f\x07\xe3\xbe\xef\xf9\x00" +
	"1\xe0\x98\xd1Y\xd3q\x1a\xf1\xc5[\x83\xc7\xe7\x89\xc4" +
	"\x18\x87\xc81\xe8\xcd\xc9\xd3*\xd3)\x0eqY\xe5\xc7" +
	"\xa2\xfc\xf2>\x91\x98\xe3\x10\x0b\x0c\xb2Z\x09B\xdf2" +
	"\xcb\xc4'J\x88\x13C\x9c C\xcfsf\xccr#" +
	"\xbf\xa6f\xfa\x8b\xd5\xb2\xe5\x86\xd4\x17L\x06\x9e{$" +
	"\x19\xec\xdb\xcb\x8eD\x80\xca\x9d\xa6\xdc\xa1\xe3\xac\xf4D" +
	"\x9aX\xb2\xe0\x95jG\xb0\xb2\xd1\xb7\x81B\xcc+\xd5" +
	"\x14W\\\xca\x08,M$F9\xc4\x14C\x02\xbfd" +
	"D61\xdc\xc6M\xb0\xba\x8c\xd0:y\x93\xa1\xb5\x1a" +
	"6\xed\x8f\x14l\xd7\xf4kH\xb5\xef\x96\x80\x14A\xfa" +
	"V\xe0U\xfd\xe8V\x8e\xdbv\xa6\xf19\xeb\xb9\xc9&" +
	"Y\xc7\xc2\xd3\xfb\x0b\x1f\xec\xc8\xbd_\xf98\xc5!\x86" +
	"\x18\x92%34[\xad\xcbv\xd9\x9a\xabU:\xa3\xfd" +
	"\x1d\x00\x00\xff\xff%\x9f\x01\x1b"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_a1c0157e2a1e0001,
		Nodes: []uint64{
			0x85c13b5006b2e242,
			0x881f943cd35fcd99,
			0x996d5ba767819739,
			0xa84e63fd0cceabc1,
			0xb9a1426ce3f54711,
			0xe004d79355ac5adb,
		},
		Compressed: true,
	})
}
