#!/usr/bin/env node
/**
 * Compile a consumer's `cluster.capnp` into a typed TS module.
 *
 * Modeled after `scripts/build-manifest.mjs`. Same pipeline shape:
 *
 *   <repo>/cluster.capnp
 *           │
 *           │  capnp eval -o json
 *           ▼
 *   { metadata, bundles, wires, storage }    (JSON intermediate)
 *           │
 *           │  this script
 *           ▼
 *   src/generated/cluster.ts                  (typed TS module)
 *
 * The TS module re-exports a `cluster` const typed as the schema's
 * `Cluster`, validated via `validateCluster()` from cluster-types.ts.
 *
 * Usage:
 *   node scripts/build-cluster.mjs
 *
 * Env vars (all optional):
 *   CLUSTER_MANIFEST     path to consumer cluster.capnp     (default: ./cluster.capnp)
 *   CLUSTER_SCHEMA       path to manifest/cluster.capnp     (default: ./manifest/cluster.capnp)
 *   CLUSTER_OUTPUT       where to write the generated TS    (default: ./src/generated/cluster.ts)
 *   CLOISTER_SCHEMA_ROOT root for capnp -I imports          (default: parent of CLUSTER_SCHEMA's dir)
 */

import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const REPO          = process.cwd();
const MANIFEST_FILE = process.env.CLUSTER_MANIFEST     ?? resolve(REPO, "cluster.capnp");
const SCHEMA_FILE   = process.env.CLUSTER_SCHEMA       ?? resolve(REPO, "manifest/cluster.capnp");
const OUTPUT_FILE   = process.env.CLUSTER_OUTPUT       ?? resolve(REPO, "src/generated/cluster.ts");
const SCHEMA_ROOT   = process.env.CLOISTER_SCHEMA_ROOT ?? resolve(dirname(SCHEMA_FILE), "../..");

let json;
try {
  const stdout = execFileSync(
    "capnp",
    ["eval", "-I", SCHEMA_ROOT, "--no-standard-import", MANIFEST_FILE, "cluster", "-o", "json"],
    { encoding: "utf8" },
  );
  json = JSON.parse(stdout);
} catch (e) {
  const stderr = e.stderr?.toString?.() ?? String(e);
  console.error(`build-cluster: capnp eval failed`);
  console.error(stderr);
  process.exit(1);
}

// Defensive shape check + normalization. capnp eval's JSON emits
// `transport: {"uds": null}` for the void union variant — the TS shape
// already accepts this. Nothing to transform on this path.

// Write the TS module.
const body = JSON.stringify(json, null, 2);
const out = `// SPDX-License-Identifier: AGPL-3.0-or-later
//
// AUTO-GENERATED by scripts/build-cluster.mjs. Do NOT edit by hand.
// Regenerate via \`task cluster:manifest\` after editing cluster.capnp.
//
// Source: cluster.capnp (consumer) → manifest/cluster.capnp (schema).
// See ADR-0009 + cloister-be0607 for the deployment-descriptor design.

// Side-effect import: keeps cluster.zod.ts in the dependency graph
// so \`task lint\`'s tsc pass type-checks the schema-bridge codegen
// alongside this legacy capnp-eval output. Today nothing here uses
// the zod schemas; this is the structural anchor for the migration
// off hand-authored cluster-types.ts. Once consumers move to importing
// types from ./cluster.zod.js directly, cluster-types.ts can shrink
// to a re-export shim and eventually retire. The codegen tool lives
// at tools/schema-bridge/ — see its README for the fail-fast
// invariant and what's mapped today.
import type {} from "./cluster.zod.js";

import type { Cluster } from "../manifest/cluster-types.js";

export const cluster: Cluster = ${body} as const;
`;

mkdirSync(dirname(OUTPUT_FILE), { recursive: true });
writeFileSync(OUTPUT_FILE, out);
console.log(`build-cluster: wrote ${OUTPUT_FILE.replace(REPO + "/", "")}`);
console.log(`build-cluster:   ${json.metadata?.name ?? "?"} v${json.metadata?.version ?? "?"}`);
console.log(`build-cluster:   ${json.bundles?.length ?? 0} bundle(s), ${json.wires?.length ?? 0} wire(s)`);
