#!/usr/bin/env node
/**
 * Emit a docker-compose.yaml (containerd/podman/nerdctl-compatible)
 * from `cluster.capnp`. First deployment-shape emitter for
 * cloister-be0607a.
 *
 * Pipeline:
 *   src/generated/cluster.ts → this script → cluster.compose.yaml
 *
 * Validates the cluster manifest first (via validateCluster from
 * cluster-types.ts). Emits one service per Bundle, shared volume for
 * UDS sockets + DO storage, ports for httpPort > 0.
 *
 * Targets the OCI compose spec — no docker-specific directives. Works
 * with:
 *   nerdctl compose up    (containerd directly)
 *   podman compose up     (daemonless)
 *   docker compose up     (docker, if you have it)
 *
 * Usage:
 *   node scripts/emit-compose.mjs
 *   → writes cluster.compose.yaml in the repo root.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";

const REPO       = process.cwd();
const INPUT_PATH = resolve(REPO, "src/generated/cluster.ts");
const OUTPUT     = process.env.COMPOSE_OUTPUT ?? resolve(REPO, "cluster.compose.yaml");

// Use a dynamic import via file:// URL so the generated TS resolves
// through the same module loader the build uses. The generated module
// is `export const cluster: Cluster = {...}` — we read it directly.
const mod = await import(pathToFileURL(INPUT_PATH).href).catch((e) => {
  console.error("emit-compose: failed to load cluster manifest");
  console.error(`  tried: ${INPUT_PATH}`);
  console.error("  did you run `task cluster:manifest`?");
  console.error(e?.message ?? e);
  process.exit(1);
});
const cluster = mod.cluster;

const { validateCluster } = await import(pathToFileURL(resolve(REPO, "src/manifest/cluster-types.ts")).href);
validateCluster(cluster);

// ── Emit ──────────────────────────────────────────────────────────────────
//
// Compose spec shape — `services` is a map keyed by service name. Each
// service has:
//   image:        OCI ref
//   command:      entrypoint args (overrides Dockerfile CMD)
//   ports:        host:container TCP forwards (only for httpPort > 0)
//   volumes:      shared mounts (UDS dir + DO storage)
//   environment:  env-var map (includes wire bindings)
//
// One named volume for DO storage + one for the UDS socket dir. Both
// are shared by every container that needs them.

const lines = [];
lines.push(`# AUTO-GENERATED by scripts/emit-compose.mjs. Do NOT edit by hand.`);
lines.push(`# Regenerate via \`task cluster:emit\` after editing cluster.capnp.`);
lines.push(`#`);
lines.push(`# Cluster: ${cluster.metadata.name} v${cluster.metadata.version}`);
lines.push(`# ${cluster.bundles.length} bundle(s), ${cluster.wires.length} wire(s)`);
lines.push(``);
lines.push(`name: ${cluster.metadata.name}`);
lines.push(``);
lines.push(`services:`);

for (const b of cluster.bundles) {
  if (!("external" in b.kind)) {
    // workerd-bundle kind is in-process; nothing to emit at the
    // compose level — it runs inside the cloister-router service.
    continue;
  }
  const ext = b.kind.external;
  lines.push(`  ${b.name}:`);
  lines.push(`    image: ${ext.image}`);
  lines.push(`    container_name: cloister-${b.name}`);
  lines.push(`    labels:`);
  lines.push(`      - "cloister.bundle=${b.name}"`);
  lines.push(`      - "cloister.tier=${b.tier}"`);
  lines.push(`      - "cloister.description=${ext.image} — ${b.description}"`);

  // Entrypoint args
  if (ext.args.length > 0) {
    lines.push(`    command:`);
    for (const a of ext.args) lines.push(`      - ${JSON.stringify(a)}`);
  }

  // Port forwards (only for bundles with TCP listeners)
  if (ext.httpPort > 0) {
    lines.push(`    ports:`);
    lines.push(`      - "${ext.httpPort}:${ext.httpPort}"`);
  }

  // Volumes: every bundle gets the UDS dir + the DO storage path.
  lines.push(`    volumes:`);
  lines.push(`      - cloister-uds:/run/cloister-uds`);
  // Only cloister-router needs DO storage (it's the only bundle that
  // hosts DOs). Identify by tier=hypervisor AND ipcSocket starting
  // with the router prefix — a simple convention; future bundles
  // that need their own storage path declare it explicitly via a
  // storage policy override (not yet schemaed).
  if (b.name === "cloister-router") {
    lines.push(`      - cloister-do:${cluster.storage.doStoragePath || "/var/lib/cloister/do"}`);
  }

  // Environment: wire bindings + bundle-declared env
  const envVars = [];
  for (const w of cluster.wires) {
    if (w.from !== b.name) continue;
    const target = cluster.bundles.find(x => x.name === w.to);
    if (target && "external" in target.kind && target.kind.external.ipcSocket) {
      envVars.push(`${w.binding}=${target.kind.external.ipcSocket}`);
    } else if (target && "external" in target.kind && target.kind.external.httpPort > 0) {
      envVars.push(`${w.binding}=http://${w.to}:${target.kind.external.httpPort}`);
    }
  }
  for (const e of ext.env) envVars.push(`${e.name}=${e.value}`);
  if (envVars.length > 0) {
    lines.push(`    environment:`);
    for (const e of envVars) lines.push(`      - ${JSON.stringify(e)}`);
  }
  lines.push(``);
}

lines.push(`volumes:`);
lines.push(`  cloister-uds:`);
lines.push(`    driver: local`);
lines.push(`    # tmpfs is fine — UDS sockets are ephemeral; recreated on container start`);
lines.push(`  cloister-do:`);
lines.push(`    driver: local`);
lines.push(`    # SQLite DO storage — survives container restarts; backup target`);

const body = lines.join("\n") + "\n";
mkdirSync(dirname(OUTPUT), { recursive: true });
writeFileSync(OUTPUT, body);
console.log(`emit-compose: wrote ${OUTPUT.replace(REPO + "/", "")}`);
console.log(`emit-compose:   ${cluster.bundles.filter(b => "external" in b.kind).length} external bundle(s)`);
