// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Test helper: mint a fully-signed cloister /mcp request envelope.
//
// Used by mcp.test.ts (and any future test that needs to exercise the
// always-on lease middleware) so each test gets a fresh nonce + ts +
// signature without manually orchestrating Web Crypto JWK imports +
// canonical-bytes builds.
//
// Cert + ephemeral keypair come from `test/wire/fixtures/cert-chain.ts`
// (auto-generated by `task rs:sign:fixtures` from a fixed RNG seed).
// The ephemeral private seed is exported as EPHEMERAL_PRIV_SEED_B64
// for exactly this purpose.
//
// Each call uses a fresh nonce so the seen_nonces replay-defense
// doesn't reject the second call. Caller can pin the timestamp via
// `tsMs` for tests that need a specific clock; default is to derive
// from a value inside the cert validity window.

import {
  CERT_ADMIN_B64,
  CERT_FULL_B64,
  EPHEMERAL_PRIV_SEED_B64,
  EPHEMERAL_PUBKEY_B64,
  NOT_BEFORE,
  SAMPLE_URL,
} from "../wire/fixtures/cert-chain.js";

interface SignedRequestArgs {
  method: string;
  params?: unknown;
  id?: string | number | null;
  url?: string;
  tsMs?: number;
  nonce?: Uint8Array;
  certB64?: string;
}

export interface SignedRequestResult {
  request: Request;
  body: string;
  nowMs: number;
}

let ephemeralKey: CryptoKey | null = null;

async function getEphemeralKey(): Promise<CryptoKey> {
  if (ephemeralKey) return ephemeralKey;
  const jwk: JsonWebKey = {
    kty: "OKP",
    crv: "Ed25519",
    d:   EPHEMERAL_PRIV_SEED_B64,
    x:   EPHEMERAL_PUBKEY_B64,
  };
  ephemeralKey = await crypto.subtle.importKey(
    "jwk", jwk, { name: "Ed25519" }, false, ["sign"],
  );
  return ephemeralKey;
}

function b64uEncode(bytes: Uint8Array): string {
  let bin = "";
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]!);
  return btoa(bin).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function canonicalBytes(
  method: string, url: string, ts: number, nonceB64: string, body: string,
): Uint8Array {
  return new TextEncoder().encode(`${method}\n${url}\n${ts}\n${nonceB64}\n${body}`);
}

export const DEFAULT_NOW_MS = (NOT_BEFORE + 100) * 1000;

let nonceCounter = 0;
function freshNonce(): Uint8Array {
  const out = new Uint8Array(16);
  const seed = ++nonceCounter;
  for (let i = 0; i < 16; i++) out[i] = (seed + i * 31) & 0xFF;
  return out;
}

export async function signedMcpRequest(args: SignedRequestArgs): Promise<SignedRequestResult> {
  const id     = args.id     ?? 1;
  const url    = args.url    ?? SAMPLE_URL;
  const tsMs   = args.tsMs   ?? DEFAULT_NOW_MS;
  const nonce  = args.nonce  ?? freshNonce();
  const nonceB64 = b64uEncode(nonce);
  const body = JSON.stringify({
    jsonrpc: "2.0",
    id,
    method: args.method,
    params: args.params,
  });

  const canonical = canonicalBytes("POST", url, tsMs, nonceB64, body);
  const key = await getEphemeralKey();
  const sigBytes = new Uint8Array(
    (await crypto.subtle.sign("Ed25519", key, canonical as BufferSource)) as ArrayBuffer,
  );

  const request = new Request(url, {
    method: "POST",
    headers: {
      "content-type":   "application/json",
      "authorization":  `Signet ${args.certB64 ?? CERT_FULL_B64}`,
      "x-signet-sig":   b64uEncode(sigBytes),
      "x-signet-ts":    String(tsMs),
      "x-signet-nonce": nonceB64,
    },
    body,
  });

  return { request, body, nowMs: tsMs };
}

export { CERT_ADMIN_B64 };
