# cloister.capnp — AUTO-GENERATED by scripts/emit-cloister-capnp.mjs
# Per ADR-0031 (cloister-345ad1 Phase 2 + cloister-c919d7 Phase 4a).
#
# Source: cluster.toml [[routes]] + [gateway] — the operator-authored
# route list + Gateway-level surface (metadata + actor + policy).
# When [gateway] is absent / all-empty, the emitter falls through to
# the ART-default template (back-compat for pre-Phase-4a cluster.toml).
# The cluster.lock.toml [[generated_backends]] overlay is applied
# DOWNSTREAM at `task manifest` time by scripts/build-manifest.mjs;
# this file carries only the cluster.toml-declared routes.
#
# Do NOT edit by hand — your edits will be overwritten on the next emitter run.
# To regenerate: `task emit:cloister-capnp`.

@0xa1c0157e1a1f0001;
using Cloister = import "/cloister/manifest/cloister.capnp";

const gateway :Cloister.Gateway = (
  metadata = (name = "cloister-multi-tenant-smoke", version = "0.1.0"),

  actor = (
    fingerprint     = "",
    algorithm       = "ed25519",
    pubkeyBinding   = "",
    attestationRepo = "",
    tunnelEndpoint  = "",
  ),

  policy = (
    maxCertLifetimeSeconds = 300,
    requireInterlock       = false,
    minAlgorithm           = "ed25519",
  ),

  routes = [
    ( path = "/health", kind = (health = void) ),
    ( path = "/",
      kind = (tenantDispatch = (
        tenants = [
          ( name       = "alice",
            mode       = "sni",
            matchValue = "alice.cluster.example",
            binding    = "T_ALICE" ),
          ( name       = "bob",
            mode       = "path-prefix",
            matchValue = "/t/bob",
            binding    = "T_BOB" )
        ],
      )),
    )
  ],
);
