// scripts/test/cluster-toml-roundtrip.test.mjs
//
// Bidi TOML ↔ cluster.ts roundtrip tests (cloister-ae06f3, ADR-0025).
//
// Run with:
//   pnpm exec tsx --test scripts/test/cluster-toml-roundtrip.test.mjs
//
// Lives under scripts/test/ (not test/) for the same reason
// cli-init.test.mjs and lint-bundle-isolation.test.mjs do: vitest-
// pool-workers runs inside workerd which has no `node:fs`,
// `node:child_process`, or `@iarna/toml`. Node-native test runner +
// tsx loader (so the .ts zod schema can be imported).
//
// Phase 2 baseline: the stub scripts throw `not implemented`; every
// behavioral test below SHOULD FAIL today. Phases 3-5 turn them
// green one tranche at a time. Phase 5 closes the loop with byte-
// equal canonical roundtrip.

import { test } from "node:test";
import { strict as assert } from "node:assert";
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  parseTomlToCluster,
  renderClusterTs,
} from "../toml-to-cluster.mjs";
import { clusterToToml } from "../cluster-to-toml.mjs";
import { ClusterSchema } from "../../src/generated/cluster.zod.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "..", "..");
const TSX_BIN = resolve(REPO_ROOT, "node_modules/.bin/tsx");
const TOML_TO_CLUSTER = resolve(REPO_ROOT, "scripts/toml-to-cluster.mjs");
const CLUSTER_TO_TOML = resolve(REPO_ROOT, "scripts/cluster-to-toml.mjs");

// ── Fixtures ──────────────────────────────────────────────────────────────

/** A minimal cluster shape that passes ClusterSchema. */
function minimalCluster() {
  return {
    metadata: { name: "test-cluster", version: "0.0.1" },
    bundles: [
      {
        name: "alpha",
        description: "A test bundle",
        tier: "cluster",
        holdsCredential: [],
        workerdServiceName: "",
        hypervisorRationale: "",
        kind: {
          external: {
            image: "alpha:0.1",
            ipcSocket: "/run/alpha.sock",
            httpPort: 0,
            args: [],
            env: [],
          },
        },
      },
    ],
    wires: [
      {
        from: "alpha",
        to: "alpha",
        binding: "SELF",
        transport: { uds: null },
      },
    ],
    storage: { doStoragePath: "/data/do" },
    inputs: [], // ADR-0026 / cloister-cf7a3b Phase 1a — required schema field
    routes: [], // cloister-345ad1 / ADR-0031 Phase 2 — required schema field
  };
}

/** Cluster covering both union variants for kind + transport. */
function richCluster() {
  return {
    metadata: { name: "rich", version: "0.0.2" },
    bundles: [
      {
        name: "router",
        description: "router bundle",
        tier: "hypervisor",
        holdsCredential: ["VAULT"],
        workerdServiceName: "router",
        hypervisorRationale: "Mediates all traffic. Singleton.",
        kind: {
          external: {
            image: "router:0.1",
            ipcSocket: "/run/router.sock",
            httpPort: 8787,
            args: ["--ipc-socket", "/run/router.sock"],
            env: [{ name: "DEBUG", value: "1" }],
          },
        },
      },
      {
        name: "tool",
        description: "tool bundle",
        tier: "cluster",
        holdsCredential: [],
        workerdServiceName: "",
        hypervisorRationale: "",
        kind: { workerd: { entryPoint: "src/bundles/tool/index.ts" } },
      },
    ],
    wires: [
      {
        from: "router",
        to: "tool",
        binding: "TOOL",
        transport: { uds: null },
      },
      {
        from: "router",
        to: "router",
        binding: "LOOPBACK",
        transport: { leylineNet: null },
      },
    ],
    storage: { doStoragePath: "/data/do" },
    inputs: [], // ADR-0026 / cloister-cf7a3b Phase 1a — required schema field
    routes: [], // cloister-345ad1 / ADR-0031 Phase 2 — required schema field
  };
}

// ── Contract 1: forward parse + validate + render ─────────────────────────

test("toml-to-cluster: parses TOML, validates via ClusterSchema, returns Cluster object", async () => {
  // Hardcoded TOML (not generated by the writer) so this test
  // exercises the READER in isolation — independent of Phase 4.
  const toml = `
[metadata]
name = "test-cluster"
version = "0.0.1"

[[bundles]]
description = "A test bundle"
holdsCredential = []
hypervisorRationale = ""
kind = "external"
name = "alpha"
tier = "cluster"
workerdServiceName = ""

[bundles.external]
args = []
env = []
httpPort = 0
image = "alpha:0.1"
ipcSocket = "/run/alpha.sock"

[[wires]]
binding = "SELF"
from = "alpha"
to = "alpha"
transport = "uds"

[storage]
doStoragePath = "/data/do"
`;
  const parsed = await parseTomlToCluster(toml);

  // The parsed result must match the schema-validated shape.
  const validated = ClusterSchema.parse(parsed);
  assert.equal(validated.metadata.name, "test-cluster");
  assert.equal(validated.bundles.length, 1);
  assert.equal(validated.bundles[0].name, "alpha");
  // Union shape (un-flattened from the TOML kind = "external" + [bundles.external]):
  assert.ok(
    "external" in validated.bundles[0].kind,
    "bundle.kind must be the { external: {...} } union shape after un-flattening",
  );
  assert.equal(validated.bundles[0].kind.external.image, "alpha:0.1");
  // Wire transport (un-flattened from transport = "uds"):
  assert.deepEqual(validated.wires[0].transport, { uds: null });
});

test("toml-to-cluster: renderClusterTs emits the same shape as scripts/build-cluster.mjs", () => {
  const c = minimalCluster();
  const ts = renderClusterTs(c);
  // Header + import + export const cluster: Cluster = {...} as const;
  assert.match(ts, /AUTO-GENERATED/);
  assert.match(ts, /import type \{ Cluster \} from "..\/manifest\/cluster-types.js";/);
  assert.match(ts, /export const cluster: Cluster = \{[\s\S]+\} as const;/);
  // The data body itself must include the cluster name.
  assert.match(ts, /"name": "test-cluster"/);
});

// ── Contract 2: schema-violation rejection ────────────────────────────────

test("toml-to-cluster: rejects TOML that violates ClusterSchema with a clear error", async () => {
  // Missing required `metadata.name` field.
  const bad = `
[metadata]
version = "0.0.1"

[storage]
doStoragePath = "/data/do"
`;
  await assert.rejects(
    () => parseTomlToCluster(bad),
    (err) => {
      // Error message must cite the field path `metadata.name`
      // (not just any field containing "name") so operators see
      // the location precisely. Tightened per skeptic-agent N5.
      return /metadata\.name/.test(err.message);
    },
    "expected a schema-validation error citing the missing 'metadata.name' field",
  );
});

// ── Contract 3: semantic wire-ref rejection ───────────────────────────────

test("toml-to-cluster: rejects TOML where a wire references a nonexistent bundle", async () => {
  // Wire.from references a bundle that isn't declared. zod doesn't
  // catch this (schema lets any string in wire.from); the semantic
  // pass must reject it.
  const bad = `
[metadata]
name = "test"
version = "0.0.1"

[[bundles]]
name = "real"
description = "exists"
tier = "cluster"
holdsCredential = []
workerdServiceName = ""
hypervisorRationale = ""
kind = "external"

[bundles.external]
image = "real:0.1"
ipcSocket = ""
httpPort = 0
args = []
env = []

[[wires]]
from = "ghost"
to = "real"
binding = "X"
transport = "uds"

[storage]
doStoragePath = "/data/do"
`;
  await assert.rejects(
    () => parseTomlToCluster(bad),
    (err) => /ghost/.test(err.message) || /unknown.*bundle/i.test(err.message),
    "expected a semantic error citing the unknown bundle 'ghost'",
  );
});

// ── Contract 4: canonical write is deterministic ──────────────────────────

test("cluster-to-toml: emits canonical TOML (deterministic key order — two calls produce byte-identical output)", () => {
  const c = richCluster();
  const t1 = clusterToToml(c);
  const t2 = clusterToToml(c);
  assert.equal(t1, t2, "canonical output must be byte-stable across calls");
});

test("cluster-to-toml: canonical TOML has metadata before bundles before wires before storage", () => {
  const c = richCluster();
  const t = clusterToToml(c);
  const iMeta = t.indexOf("[metadata]");
  const iBund = t.indexOf("[[bundles]]");
  const iWire = t.indexOf("[[wires]]");
  const iStor = t.indexOf("[storage]");
  assert.ok(iMeta >= 0 && iBund > iMeta, "metadata must come before bundles");
  assert.ok(iWire > iBund, "bundles must come before wires");
  assert.ok(iStor > iWire, "wires must come before storage");
});

// ── Contract 5: discriminated unions flatten to kind = "<variant>" ────────

test("cluster-to-toml: discriminated unions emit as kind = \"<variant>\" + [bundle.<variant>] sibling", () => {
  const c = richCluster();
  const t = clusterToToml(c);

  // The router bundle is { external: {...} } — must appear as
  // kind = "external" + a [bundles.external] subtable with image=.
  assert.match(t, /kind = "external"/, "external bundle must emit kind = \"external\"");
  assert.match(t, /\[bundles\.external\]/, "external bundle must have a [bundles.external] subtable");
  assert.match(t, /image = "router:0.1"/, "subtable must contain the payload fields");

  // The tool bundle is { workerd: {...} }.
  assert.match(t, /kind = "workerd"/, "workerd bundle must emit kind = \"workerd\"");
  assert.match(t, /\[bundles\.workerd\]/, "workerd bundle must have a [bundles.workerd] subtable");
  assert.match(t, /entryPoint = "src\/bundles\/tool\/index\.ts"/);
});

// ── Contract 6: void union variants emit just the discriminator ───────────

test("cluster-to-toml: void union variants (transport.uds, transport.leylineNet) emit as transport = \"<variant>\" with no payload subtable", () => {
  const c = richCluster();
  const t = clusterToToml(c);

  // Both void variants must appear as a string tag, NOT as a table
  // or null sentinel. Per ADR-0025 §Discriminated unions.
  assert.match(t, /transport = "uds"/, "uds wire must emit transport = \"uds\"");
  assert.match(t, /transport = "leylineNet"/, "leylineNet wire must emit transport = \"leylineNet\"");

  // No [wires.uds] or [wires.leylineNet] subtables for void variants.
  assert.equal(t.indexOf("[wires.uds]"), -1, "void variants must NOT emit a payload subtable");
  assert.equal(t.indexOf("[wires.leylineNet]"), -1, "void variants must NOT emit a payload subtable");
});

// ── Contract 7: TOML → cluster.ts → TOML is byte-equal ────────────────────

test("roundtrip: canonical TOML → cluster object → canonical TOML produces byte-equal output", async () => {
  const c = richCluster();
  const t1 = clusterToToml(c);
  const obj = await parseTomlToCluster(t1);
  const t2 = clusterToToml(obj);
  assert.equal(t2, t1, "canonical roundtrip must be byte-equal");
});

// ── Contract 8: cluster.ts → TOML → cluster.ts is semantically equivalent ──

test("roundtrip: cluster object → TOML → cluster object is semantically equivalent (zod-validated identical shape)", async () => {
  const c = richCluster();
  const t = clusterToToml(c);
  const back = await parseTomlToCluster(t);

  // Both shapes pass ClusterSchema.
  const a = ClusterSchema.parse(c);
  const b = ClusterSchema.parse(back);

  // After zod-parse, the structural shape must be identical.
  assert.deepEqual(b, a, "roundtrip must preserve all data faithfully");
});

// ── Contract 9: duplicate bundle names rejected ──────────────────────────

test("toml-to-cluster: rejects TOML with duplicate bundle names", async () => {
  // `wires = []` at the top is required by TOML 1.0.0 (top-level
  // scalars must precede any table sections); zod also requires
  // `wires` to be present (empty is fine).
  const bad = `wires = []

[metadata]
name = "test"
version = "0.0.1"

[[bundles]]
name = "twin"
description = "first"
tier = "cluster"
holdsCredential = []
workerdServiceName = ""
hypervisorRationale = ""
kind = "external"
[bundles.external]
image = "twin:0.1"
ipcSocket = "/twin1.sock"
httpPort = 0
args = []
env = []

[[bundles]]
name = "twin"
description = "second — duplicate name"
tier = "cluster"
holdsCredential = []
workerdServiceName = ""
hypervisorRationale = ""
kind = "external"
[bundles.external]
image = "twin:0.2"
ipcSocket = "/twin2.sock"
httpPort = 0
args = []
env = []

[storage]
doStoragePath = "/data/do"
`;
  await assert.rejects(
    () => parseTomlToCluster(bad),
    (err) => /bundle name "twin" is declared more than once/.test(err.message),
    "expected duplicate-bundle-name rejection citing the collision",
  );
});

// ── Contract 10: duplicate wire bindings rejected ────────────────────────

test("toml-to-cluster: rejects TOML with duplicate wire bindings", async () => {
  const bad = `
[metadata]
name = "test"
version = "0.0.1"

[[bundles]]
name = "alpha"
description = "a"
tier = "cluster"
holdsCredential = []
workerdServiceName = ""
hypervisorRationale = ""
kind = "external"
[bundles.external]
image = "alpha:0.1"
ipcSocket = "/alpha.sock"
httpPort = 0
args = []
env = []

[[wires]]
from = "alpha"
to = "alpha"
binding = "DUPED"
transport = "uds"

[[wires]]
from = "alpha"
to = "alpha"
binding = "DUPED"
transport = "uds"

[storage]
doStoragePath = "/data/do"
`;
  await assert.rejects(
    () => parseTomlToCluster(bad),
    (err) => /wire binding "DUPED" is declared more than once/.test(err.message),
    "expected duplicate-wire-binding rejection citing the collision",
  );
});

// ── Contract 11: empty cluster roundtrips deterministically ──────────────

test("roundtrip: empty bundles/wires arrays are byte-equal across roundtrip (TOML hoists them per spec — known artifact, documented in ADR-0025 §Canonicalization)", async () => {
  const empty = {
    metadata: { name: "empty", version: "0.0.1" },
    bundles: [],
    wires: [],
    storage: { doStoragePath: "/data/do" },
    inputs: [], // ADR-0026 / cloister-cf7a3b Phase 1a — required schema field
    routes: [], // cloister-345ad1 / ADR-0031 Phase 2 — required schema field
  };
  const t1 = clusterToToml(empty);
  const back = await parseTomlToCluster(t1);
  const t2 = clusterToToml(back);
  assert.equal(t2, t1, "empty-cluster canonical form must be byte-stable");
  // Confirm zod validates the parsed-back shape too.
  const validated = ClusterSchema.parse(back);
  assert.deepEqual(validated, empty);
});

// ── cloister-fe891f: Taskfile cluster:toml chain canonicalizes operator-edited TOML ──
//
// Spec: `task cluster:toml` MUST chain `toml-to-cluster.mjs` (forward)
// then `cluster-to-toml.mjs --write cluster.toml` (re-canonicalize) so
// operator-edited TOML lands in canonical form in one verb. Without
// the chain, an operator who types `httpPort = 9999` (which @iarna/toml
// normalizes to `9_999`) sees the drift gate fail after `task cluster:toml`
// even though the data is correct.
//
// Test exercises the chain at the script level (matches what Taskfile
// will invoke). If the scripts change such that the chain no longer
// canonicalizes in one pass, this fails. Pair with the Taskfile entry
// having BOTH commands — see Taskfile.yml `cluster:toml`.

const NON_CANONICAL_TOML = `
[metadata]
name = "fe891f-test"
version = "0.0.1"

[[bundles]]
description = "fe891f probe — non-canonical formatting"
holdsCredential = []
hypervisorRationale = ""
kind = "external"
name = "probe"
tier = "cluster"
workerdServiceName = ""

  [bundles.external]
  args = []
  env = []
  httpPort = 9999
  image = "probe:0.1"
  ipcSocket = "/run/probe.sock"

[storage]
doStoragePath = "/data/do"

[[wires]]
binding = "SELF"
from = "probe"
to = "probe"
transport = "uds"
`;

function runChain(workDir, tomlPath, tsPath) {
  // Forward: parse cluster.toml → render cluster.ts.
  const fwd = spawnSync(TSX_BIN, [TOML_TO_CLUSTER], {
    cwd: workDir,
    env: { ...process.env, CLUSTER_TOML: tomlPath, CLUSTER_OUTPUT: tsPath },
    encoding: "utf8",
  });
  if (fwd.status !== 0) {
    throw new Error(`toml-to-cluster failed: exit=${fwd.status}\nstderr:\n${fwd.stderr}\nstdout:\n${fwd.stdout}`);
  }
  // Reverse: render cluster.ts → canonical cluster.toml (overwriting input).
  const rev = spawnSync(TSX_BIN, [CLUSTER_TO_TOML, "--write", tomlPath], {
    cwd: workDir,
    env: { ...process.env, CLUSTER_TS: tsPath },
    encoding: "utf8",
  });
  if (rev.status !== 0) {
    throw new Error(`cluster-to-toml failed: exit=${rev.status}\nstderr:\n${rev.stderr}\nstdout:\n${rev.stdout}`);
  }
}

test("cloister-fe891f: chained workflow canonicalizes non-canonical operator-edited TOML in one pass", () => {
  const tmp = mkdtempSync(resolve(tmpdir(), "fe891f-"));
  const tomlPath = resolve(tmp, "cluster.toml");
  const tsPath = resolve(tmp, "cluster.ts");

  try {
    writeFileSync(tomlPath, NON_CANONICAL_TOML);

    // Single chain pass = the Taskfile `cluster:toml` workflow post-fix.
    runChain(tmp, tomlPath, tsPath);

    const afterChain = readFileSync(tomlPath, "utf8");

    // 1. The chain rewrote the file (operator's non-canonical input
    //    was normalized).
    assert.notEqual(
      afterChain,
      NON_CANONICAL_TOML,
      "chain must rewrite operator-edited TOML to canonical form",
    );

    // 2. The canonical form normalizes the integer (httpPort 9999 → 9_999
    //    per @iarna/toml thousand-separator behavior).
    assert.match(
      afterChain,
      /httpPort = 9_999/,
      "canonical form should use TOML's thousand-separator for integers ≥1000",
    );

    // 3. Second chain pass is a no-op (canonical is the fixed point).
    runChain(tmp, tomlPath, tsPath);
    const afterSecondChain = readFileSync(tomlPath, "utf8");
    assert.equal(
      afterSecondChain,
      afterChain,
      "canonical TOML must be a fixed point of the chain (second pass = no-op)",
    );
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
});

test("cloister-fe891f: Taskfile cluster:toml entry has BOTH legs of the chain", () => {
  // Pins the Taskfile config so a future edit that drops the
  // canonicalize step fails CI immediately. Companion to the
  // behavior test above — behavior tests the contract; this tests
  // the wire-up.
  const taskfile = readFileSync(resolve(REPO_ROOT, "Taskfile.yml"), "utf8");

  // Extract the cluster:toml: block (up to the next top-level entry).
  // Match from `  cluster:toml:` (indented) through the next blank line
  // followed by a non-indented or differently-indented key.
  const blockMatch = taskfile.match(/^  cluster:toml:\n([\s\S]*?)(?=^  [\w:-]+:|^\S)/m);
  assert.ok(blockMatch, "Taskfile must contain a cluster:toml: entry");
  const block = blockMatch[1];

  assert.match(
    block,
    /toml-to-cluster\.mjs/,
    "cluster:toml must invoke the forward leg (toml-to-cluster.mjs)",
  );
  assert.match(
    block,
    /cluster-to-toml\.mjs[^\n]*--write[^\n]*cluster\.toml/,
    "cluster:toml must chain the re-canonicalize step (cluster-to-toml.mjs --write cluster.toml) — per cloister-fe891f",
  );
});

// ── cloister-cf7a3b Phase 1a: [inputs.*] schema lands in bidi pipeline ───

test("inputs: TOML [inputs.<name>] table roundtrips to InputSpec[] and back to byte-equal canonical TOML", async () => {
  const { parseTomlToCluster, renderClusterTs } = await import("../toml-to-cluster.mjs");
  const { clusterToToml } = await import("../cluster-to-toml.mjs");

  // Inline TOML fixture covering: ref-only (no version), version-pinned,
  // digest-pinned (defense-in-depth), dev-loop `from` override, and the
  // lego-blocks provides/requires capability declarations.
  const tomlIn = `
[metadata]
name    = "inputs-fixture"
version = "0.0.1"

[[bundles]]
name                = "router"
description         = "self-loop"
tier                = "cluster"
holdsCredential     = []
workerdServiceName  = ""
hypervisorRationale = ""
kind                = "external"
  [bundles.external]
  image     = "router:0.1"
  ipcSocket = "/run/r.sock"
  httpPort  = 0
  args      = []
  env       = []

[[wires]]
from      = "router"
to        = "router"
binding   = "SELF"
transport = "uds"

[storage]
doStoragePath = "/data/do"

[inputs.rosary]
ref      = "io.github.jamestexas/rosary"
version  = "^0.1"
provides = ["cloister/mcp-tool/v1"]
requires = ["cloister/credential-isolation/v1"]

[inputs.python-tools]
ref      = "skills.sh/python"
version  = "^1.0"
digest   = "sha256:deadbeef"
provides = ["cloister/skill/v1", "cloister/python-runtime/v1"]

[inputs.local-dev]
ref     = "io.github.jamestexas/mache"
version = "^0.3"
from    = "file:///abs/path/to/mache"
`;
  const parsed = await parseTomlToCluster(tomlIn);
  assert.equal(parsed.inputs.length, 3, "expected 3 inputs after unflatten");
  const byName = Object.fromEntries(parsed.inputs.map((i) => [i.name, i]));
  assert.equal(byName.rosary.ref, "io.github.jamestexas/rosary");
  assert.equal(byName.rosary.version, "^0.1");
  assert.deepEqual(byName.rosary.provides, ["cloister/mcp-tool/v1"]);
  assert.deepEqual(byName.rosary.requires, ["cloister/credential-isolation/v1"]);
  assert.equal(byName["python-tools"].digest, "sha256:deadbeef");
  assert.equal(byName["local-dev"].from, "file:///abs/path/to/mache");

  // Reverse leg: cluster object → canonical TOML. Two stringifications
  // produce byte-identical bytes (existing deterministic-emit property
  // extends to inputs).
  const t1 = clusterToToml(parsed);
  const t2 = clusterToToml(parsed);
  assert.equal(t1, t2, "cluster-to-toml emit must be deterministic");

  // The emitted TOML carries the three [inputs.<name>] table headers.
  // Substring checks (not regex) so the intent is plain — we're
  // asserting these exact strings appear, nothing fancier.
  assert.ok(t1.includes("[inputs.rosary]"),       "missing [inputs.rosary] header");
  assert.ok(t1.includes("[inputs.python-tools]"), "missing [inputs.python-tools] header");
  assert.ok(t1.includes("[inputs.local-dev]"),    "missing [inputs.local-dev] header");

  // Forward leg is idempotent: parsing the emitted TOML returns the
  // same cluster shape (this is the load-bearing roundtrip property +
  // also implicitly proves "empty fields omitted" — if cluster-to-toml
  // emitted `digest = ""` for the rosary input, parseTomlToCluster
  // would happily re-parse it back, so the deepEqual is the real test).
  const reparsed = await parseTomlToCluster(t1);
  assert.deepEqual(reparsed.inputs, parsed.inputs, "inputs must round-trip identity");

  // renderClusterTs handles the inputs field (no crash); structural
  // check on the rendered body — re-import via dynamic eval would be
  // overkill, so we assert presence of the field via plain substring.
  const tsBody = renderClusterTs(parsed);
  assert.ok(tsBody.includes('"inputs"'), "rendered TS body must serialize the inputs field");
  // Same body re-parsed as JSON (after stripping the TS wrapper) round-trips
  // the inputs structurally.
  const jsonBody = tsBody
    .replace(/^[\s\S]*export const cluster: Cluster = /, "")
    .replace(/ as const;\s*$/, "");
  const reparsedFromTs = JSON.parse(jsonBody);
  assert.deepEqual(reparsedFromTs.inputs, parsed.inputs);
});

test("inputs: cluster.toml with NO [inputs.*] tables parses to empty inputs array (back-compat)", async () => {
  const { parseTomlToCluster } = await import("../toml-to-cluster.mjs");
  const tomlIn = `
[metadata]
name    = "no-inputs"
version = "0.0.1"

[[bundles]]
name                = "alpha"
description         = ""
tier                = "cluster"
holdsCredential     = []
workerdServiceName  = ""
hypervisorRationale = ""
kind                = "external"
  [bundles.external]
  image     = "alpha:0.1"
  ipcSocket = "/run/a.sock"
  httpPort  = 0
  args      = []
  env       = []

[[wires]]
from      = "alpha"
to        = "alpha"
binding   = "SELF"
transport = "uds"

[storage]
doStoragePath = "/data/do"
`;
  const parsed = await parseTomlToCluster(tomlIn);
  assert.deepEqual(parsed.inputs, [], "missing [inputs] table → empty array");
});

test("inputs: empty inputs array omits the [inputs] section from emitted TOML (back-compat)", async () => {
  const { clusterToToml } = await import("../cluster-to-toml.mjs");
  const cluster = {
    metadata: { name: "no-inputs", version: "0.0.1" },
    bundles: [
      {
        name: "alpha", description: "", tier: "cluster",
        holdsCredential: [], workerdServiceName: "", hypervisorRationale: "",
        kind: { external: { image: "a:0.1", ipcSocket: "/run/a", httpPort: 0, args: [], env: [] } },
      },
    ],
    wires: [{ from: "alpha", to: "alpha", binding: "SELF", transport: { uds: null } }],
    storage: { doStoragePath: "/data/do" },
    inputs: [],
    routes: [],
  };
  const toml = clusterToToml(cluster);
  // Substring check, not regex. The contract: any "[inputs" header
  // would be a sign we emitted a stray section for an empty list.
  assert.ok(!toml.includes("[inputs"), "empty inputs[] must NOT emit a [inputs] table");
});

// ── cloister-05334b (P1 of LLO arc): urlBinding + serviceBinding on InputSpec ──
//
// The transport-binding hints thread through to [[generated_backends]] rows in
// cluster.lock.toml when the resolved input carries _meta.art.cloister/v1
// (or when the heuristic fallback fires). The downstream manifest emitter
// (scripts/build-manifest.mjs) then wires the generated mcpProxy backend to
// the right env-var bindings. Schema add: append-only ordinals @7 / @8 on
// InputSpec per ADR-0004 schema-evolution rules.

test("inputs: urlBinding + serviceBinding round-trip through cluster.toml (populated)", async () => {
  const { parseTomlToCluster } = await import("../toml-to-cluster.mjs");
  const { clusterToToml } = await import("../cluster-to-toml.mjs");
  const tomlIn = `
[metadata]
name    = "with-bindings"
version = "0.0.1"

[[bundles]]
name                = "alpha"
description         = ""
tier                = "cluster"
holdsCredential     = []
workerdServiceName  = ""
hypervisorRationale = ""
kind                = "external"
  [bundles.external]
  image     = "alpha:0.1"
  ipcSocket = "/run/a.sock"
  httpPort  = 0
  args      = []
  env       = []

[[wires]]
from      = "alpha"
to        = "alpha"
binding   = "SELF"
transport = "uds"

[storage]
doStoragePath = "/data/do"

[inputs.llo]
ref            = "io.github.org/agentic-research/ley-line-open@main"
version        = "0.4.5"
urlBinding     = "LLO_MCP_URL"
serviceBinding = "LSP_MCP"
`;
  const parsed = await parseTomlToCluster(tomlIn);
  assert.equal(parsed.inputs.length, 1);
  assert.equal(parsed.inputs[0].urlBinding, "LLO_MCP_URL", "urlBinding must thread through the parse");
  assert.equal(parsed.inputs[0].serviceBinding, "LSP_MCP", "serviceBinding must thread through the parse");

  // Forward then reverse leg — round-trip preserves the bindings.
  const emitted = clusterToToml(parsed);
  assert.ok(emitted.includes('urlBinding = "LLO_MCP_URL"'), "emitted TOML must carry urlBinding");
  assert.ok(emitted.includes('serviceBinding = "LSP_MCP"'), "emitted TOML must carry serviceBinding");

  const reparsed = await parseTomlToCluster(emitted);
  assert.deepEqual(reparsed.inputs, parsed.inputs, "binding hints must round-trip identity");
});

test("inputs: omitting urlBinding + serviceBinding parses to empty strings (back-compat)", async () => {
  const { parseTomlToCluster } = await import("../toml-to-cluster.mjs");
  const { clusterToToml } = await import("../cluster-to-toml.mjs");
  const tomlIn = `
[metadata]
name    = "no-bindings"
version = "0.0.1"

[[bundles]]
name                = "alpha"
description         = ""
tier                = "cluster"
holdsCredential     = []
workerdServiceName  = ""
hypervisorRationale = ""
kind                = "external"
  [bundles.external]
  image     = "alpha:0.1"
  ipcSocket = "/run/a.sock"
  httpPort  = 0
  args      = []
  env       = []

[[wires]]
from      = "alpha"
to        = "alpha"
binding   = "SELF"
transport = "uds"

[storage]
doStoragePath = "/data/do"

[inputs.bare]
ref = "file:///tmp/foo"
`;
  const parsed = await parseTomlToCluster(tomlIn);
  assert.equal(parsed.inputs.length, 1);
  // Defaults: empty strings (canonical "unspecified" shape).
  assert.equal(parsed.inputs[0].urlBinding, "");
  assert.equal(parsed.inputs[0].serviceBinding, "");

  // Reverse leg must NOT emit empty-string bindings (canonicalization
  // drops empty fields so operators see only what they set).
  const emitted = clusterToToml(parsed);
  assert.ok(!emitted.includes("urlBinding"), "empty urlBinding must NOT appear in canonical TOML");
  assert.ok(!emitted.includes("serviceBinding"), "empty serviceBinding must NOT appear in canonical TOML");
});

test("inputs: zod strict-mode ACCEPTS urlBinding + serviceBinding (P5 follow-up — was previously a reject)", async () => {
  // Before this bead, the `.strict()` ClusterSchema rejected unknown
  // keys on InputSpec, so the resolver couldn't thread urlBinding /
  // serviceBinding from [inputs.*] through the bidi pipeline. This
  // test pins the fix.
  const { ClusterSchema } = await import("../../src/generated/cluster.zod.ts");
  const sample = {
    metadata: { name: "x", version: "0.0.1" },
    bundles: [],
    wires: [],
    storage: { doStoragePath: "/data/do" },
    inputs: [{
      name: "llo", ref: "x", version: "1", digest: "", from: "",
      provides: [], requires: [],
      urlBinding: "LLO_MCP_URL", serviceBinding: "LSP_MCP",
    }],
    routes: [], // cloister-345ad1 / ADR-0031 Phase 2 — required schema field
  };
  const out = ClusterSchema.parse(sample);
  assert.equal(out.inputs[0].urlBinding, "LLO_MCP_URL");
  assert.equal(out.inputs[0].serviceBinding, "LSP_MCP");
});
