// scripts/test/gen-adr-index.test.mjs
//
// Contract tests for scripts/gen-adr-index.mjs — the ADR index generator that
// makes docs/adr/INDEX.md a DERIVED single source of truth (cloister-1d2e0e).
//
// Run: pnpm exec tsx --test scripts/test/gen-adr-index.test.mjs
//
// Unit tests parse synthesized ADR text (covers the 26-YAML / 17-inline split
// the lenient parser must handle); one integration test asserts EVERY real ADR
// parses to a known status — the thing that must hold for generation to replace
// the hand-copied status lists.

import { test } from "node:test";
import { strict as assert } from "node:assert";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { findDuplicateNumbers, parseAdrText, buildIndexMd, readAllAdrs, STATUS_ENUM } from "../gen-adr-index.mjs";

const ADR_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "docs", "adr");

test("parseAdrText: YAML frontmatter status + title (prefix stripped)", () => {
  const t = `---\ntitle: "ADR-0034: True multi-tenant access spec"\nstatus: Proposed (2026-06-24)\ndate: 2026-06-24\n---\n\n## Context`;
  const r = parseAdrText(34, "0034-x.md", t);
  assert.equal(r.num, 34);
  assert.equal(r.title, "True multi-tenant access spec");
  assert.equal(r.status, "Proposed");
  assert.equal(r.date, "2026-06-24");
});

test("parseAdrText: inline **Status:** + heading-title fallback", () => {
  const t = `# ADR-0044 — Compute-isolation substrate\n\n- **Status:** Proposed (2026-07-08)\n`;
  const r = parseAdrText(44, "0044-x.md", t);
  assert.equal(r.title, "Compute-isolation substrate");
  assert.equal(r.status, "Proposed");
  assert.equal(r.date, "2026-07-08");
});

test("parseAdrText: first enum wins on a multi-state status line", () => {
  const t = `---\ntitle: "ADR-0045: leyline-sign"\nstatus: Amended 2026-07-09 — original premise was Proposed\n---`;
  const r = parseAdrText(45, "0045-x.md", t);
  assert.equal(r.status, "Amended"); // NOT Proposed — order matters
});

test("parseAdrText: Accepted (Phase 1) beats a later word", () => {
  const r = parseAdrText(9, "0009-x.md", `---\ntitle: x\nstatus: Accepted Phase 1; Proposed for Phase 2\n---`);
  assert.equal(r.status, "Accepted");
});

test("parseAdrText: unparseable status → em-dash sentinel", () => {
  const r = parseAdrText(99, "0099-x.md", `# ADR-0099 — Nothing\n\nno status here`);
  assert.equal(r.status, "—");
});

test("buildIndexMd: header + count + one row per ADR, date only when present", () => {
  const md = buildIndexMd([
    { num: 1, file: "0001-a.md", title: "One", status: "Accepted", date: "" },
    { num: 44, file: "0044-b.md", title: "Two", status: "Proposed", date: "2026-07-08" },
  ]);
  assert.match(md, /2 numbered ADRs/);
  assert.match(md, /GENERATED by scripts\/gen-adr-index\.mjs/);
  assert.match(md, /\| \[ADR-0001\]\(0001-a\.md\) \| One \| Accepted \|/);
  assert.match(md, /\| \[ADR-0044\]\(0044-b\.md\) \| Two \| Proposed · 2026-07-08 \|/);
});

test("readAllAdrs: EVERY real ADR parses to a known status + title (no sentinels)", () => {
  const adrs = readAllAdrs(ADR_DIR);
  assert.ok(adrs.length >= 40, `expected the full ADR set, got ${adrs.length}`);
  const unparsed = adrs.filter((a) => a.status === "—" || a.title === "(untitled)");
  assert.deepEqual(unparsed.map((a) => a.file), [], "these ADRs failed status/title extraction");
  for (const a of adrs) assert.ok(STATUS_ENUM.includes(a.status), `${a.file}: unexpected status "${a.status}"`);
});

test("findDuplicateNumbers catches two files claiming one ADR number", () => {
  // Regression: 0052-bead-algebra-convergence.md and
  // 0052-protected-resource-metadata.md both shipped as "ADR-0052", and
  // `--check` reported success because the generator only compared its own
  // output to the committed file — it never asserted number uniqueness.
  const dupes = findDuplicateNumbers([
    "0051-a.md", "0052-bead-algebra.md", "0052-protected-resource.md", "0053-c.md",
  ]);
  assert.equal(dupes.length, 1);
  assert.equal(dupes[0].num, 52);
  assert.equal(dupes[0].files.length, 2);
});

test("findDuplicateNumbers is silent on a unique set", () => {
  assert.deepEqual(findDuplicateNumbers(["0051-a.md", "0052-b.md", "0053-c.md"]), []);
});
