// Generated by schema-bridge — do not edit by hand.
// Regenerate with `task cluster:go` (runs the schema-bridge plugin).
//
// If schema-bridge errored on a construct used here,
// the codegen needs a new mapping — extend it, don't
// hand-author this file.

package cluster

import "encoding/json"

type Tier string

const (
	TierHypervisor Tier = "hypervisor"
	TierCluster    Tier = "cluster"
)

type ClusterMetadata struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

type BundleKindUnion struct {
	Workerd  *WorkerdBundle  `json:"workerd,omitempty"`
	External *ExternalBundle `json:"external,omitempty"`
}

type Bundle struct {
	Name                string          `json:"name"`
	Description         string          `json:"description"`
	Tier                Tier            `json:"tier"`
	HoldsCredential     []string        `json:"holdsCredential"`
	WorkerdServiceName  string          `json:"workerdServiceName"`
	HypervisorRationale string          `json:"hypervisorRationale"`
	PerTenant           bool            `json:"perTenant"`
	Kind                BundleKindUnion `json:"kind"`
}

type WireTransportUnion struct {
	Uds        *struct{} `json:"uds,omitempty"`
	LeylineNet *struct{} `json:"leylineNet,omitempty"`
}

func (u WireTransportUnion) MarshalJSON() ([]byte, error) {
	if u.Uds != nil {
		return []byte(`{"uds":null}`), nil
	}
	if u.LeylineNet != nil {
		return []byte(`{"leylineNet":null}`), nil
	}
	return []byte(`{}`), nil
}

func (u *WireTransportUnion) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if _, ok := raw["uds"]; ok {
		u.Uds = &struct{}{}
	}
	if _, ok := raw["leylineNet"]; ok {
		u.LeylineNet = &struct{}{}
	}
	return nil
}

type Wire struct {
	From      string             `json:"from"`
	To        string             `json:"to"`
	Binding   string             `json:"binding"`
	Transport WireTransportUnion `json:"transport"`
}

type StoragePolicy struct {
	DoStoragePath string `json:"doStoragePath"`
}

type InputSpec struct {
	Name           string      `json:"name"`
	Ref            string      `json:"ref"`
	Version        string      `json:"version"`
	Digest         string      `json:"digest"`
	From           string      `json:"from"`
	Provides       []string    `json:"provides"`
	Requires       []string    `json:"requires"`
	UrlBinding     string      `json:"urlBinding"`
	ServiceBinding string      `json:"serviceBinding"`
	Tenancy        TenancySpec `json:"tenancy"`
}

type RouteKindUnion struct {
	Health                  *struct{}                `json:"health,omitempty"`
	Mcp                     *McpRouteSpec            `json:"mcp,omitempty"`
	ServiceBindingProxy     *ServiceBindingProxySpec `json:"serviceBindingProxy,omitempty"`
	HttpProxy               *HttpProxySpec           `json:"httpProxy,omitempty"`
	WellKnownInterlace      *struct{}                `json:"wellKnownInterlace,omitempty"`
	Disclosure              *struct{}                `json:"disclosure,omitempty"`
	WellKnownIdentityBridge *struct{}                `json:"wellKnownIdentityBridge,omitempty"`
	OciRegistry             *struct{}                `json:"ociRegistry,omitempty"`
	WellKnownMcpRegistry    *struct{}                `json:"wellKnownMcpRegistry,omitempty"`
	CaBundle                *struct{}                `json:"caBundle,omitempty"`
	VaultProxy              *VaultProxySpec          `json:"vaultProxy,omitempty"`
	TenantDispatch          *TenantDispatchSpec      `json:"tenantDispatch,omitempty"`
}

func (u RouteKindUnion) MarshalJSON() ([]byte, error) {
	if u.Health != nil {
		return []byte(`{"health":null}`), nil
	}
	if u.Mcp != nil {
		return json.Marshal(map[string]any{"mcp": u.Mcp})
	}
	if u.ServiceBindingProxy != nil {
		return json.Marshal(map[string]any{"serviceBindingProxy": u.ServiceBindingProxy})
	}
	if u.HttpProxy != nil {
		return json.Marshal(map[string]any{"httpProxy": u.HttpProxy})
	}
	if u.WellKnownInterlace != nil {
		return []byte(`{"wellKnownInterlace":null}`), nil
	}
	if u.Disclosure != nil {
		return []byte(`{"disclosure":null}`), nil
	}
	if u.WellKnownIdentityBridge != nil {
		return []byte(`{"wellKnownIdentityBridge":null}`), nil
	}
	if u.OciRegistry != nil {
		return []byte(`{"ociRegistry":null}`), nil
	}
	if u.WellKnownMcpRegistry != nil {
		return []byte(`{"wellKnownMcpRegistry":null}`), nil
	}
	if u.CaBundle != nil {
		return []byte(`{"caBundle":null}`), nil
	}
	if u.VaultProxy != nil {
		return json.Marshal(map[string]any{"vaultProxy": u.VaultProxy})
	}
	if u.TenantDispatch != nil {
		return json.Marshal(map[string]any{"tenantDispatch": u.TenantDispatch})
	}
	return []byte(`{}`), nil
}

func (u *RouteKindUnion) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if _, ok := raw["health"]; ok {
		u.Health = &struct{}{}
	}
	if msg, ok := raw["mcp"]; ok {
		u.Mcp = &McpRouteSpec{}
		if err := json.Unmarshal(msg, u.Mcp); err != nil {
			return err
		}
	}
	if msg, ok := raw["serviceBindingProxy"]; ok {
		u.ServiceBindingProxy = &ServiceBindingProxySpec{}
		if err := json.Unmarshal(msg, u.ServiceBindingProxy); err != nil {
			return err
		}
	}
	if msg, ok := raw["httpProxy"]; ok {
		u.HttpProxy = &HttpProxySpec{}
		if err := json.Unmarshal(msg, u.HttpProxy); err != nil {
			return err
		}
	}
	if _, ok := raw["wellKnownInterlace"]; ok {
		u.WellKnownInterlace = &struct{}{}
	}
	if _, ok := raw["disclosure"]; ok {
		u.Disclosure = &struct{}{}
	}
	if _, ok := raw["wellKnownIdentityBridge"]; ok {
		u.WellKnownIdentityBridge = &struct{}{}
	}
	if _, ok := raw["ociRegistry"]; ok {
		u.OciRegistry = &struct{}{}
	}
	if _, ok := raw["wellKnownMcpRegistry"]; ok {
		u.WellKnownMcpRegistry = &struct{}{}
	}
	if _, ok := raw["caBundle"]; ok {
		u.CaBundle = &struct{}{}
	}
	if msg, ok := raw["vaultProxy"]; ok {
		u.VaultProxy = &VaultProxySpec{}
		if err := json.Unmarshal(msg, u.VaultProxy); err != nil {
			return err
		}
	}
	if msg, ok := raw["tenantDispatch"]; ok {
		u.TenantDispatch = &TenantDispatchSpec{}
		if err := json.Unmarshal(msg, u.TenantDispatch); err != nil {
			return err
		}
	}
	return nil
}

type Route struct {
	Path string         `json:"path"`
	Kind RouteKindUnion `json:"kind"`
}

type Gateway struct {
	Metadata GatewayMetadata `json:"metadata"`
	Actor    Actor           `json:"actor"`
	Policy   InterlacePolicy `json:"policy"`
}

type EdgeSpec struct {
	From        string `json:"from"`
	To          string `json:"to"`
	AppProtocol string `json:"appProtocol"`
	Transport   string `json:"transport"`
}

type Cluster struct {
	Metadata ClusterMetadata `json:"metadata"`
	Bundles  []Bundle        `json:"bundles"`
	Wires    []Wire          `json:"wires"`
	Storage  StoragePolicy   `json:"storage"`
	Inputs   []InputSpec     `json:"inputs"`
	Routes   []Route         `json:"routes"`
	Gateway  Gateway         `json:"gateway"`
	Edges    []EdgeSpec      `json:"edges"`
}

type WorkerdBundle struct {
	EntryPoint string `json:"entryPoint"`
}

type ExternalBundle struct {
	Image     string   `json:"image"`
	IpcSocket string   `json:"ipcSocket"`
	HttpPort  uint16   `json:"httpPort"`
	Args      []string `json:"args"`
	Env       []EnvVar `json:"env"`
}

type EnvVar struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type TenancySpec struct {
	Mode              string   `json:"mode"`
	WorkerdId         string   `json:"workerdId"`
	TrustedTier       bool     `json:"trustedTier"`
	SharesWorkerdWith []string `json:"sharesWorkerdWith"`
}

type McpRouteSpec struct {
	Backends []Backend `json:"backends"`
}

type ServiceBindingProxySpec struct {
	Binding      string `json:"binding"`
	UpstreamHost string `json:"upstreamHost"`
	StripPrefix  string `json:"stripPrefix"`
}

type HttpProxySpec struct {
	UrlBinding  string `json:"urlBinding"`
	StripPrefix string `json:"stripPrefix"`
}

type VaultProxySpec struct {
	BundleIdName string `json:"bundleIdName"`
}

type TenantDispatchSpec struct {
	Tenants []TenantDispatchRow `json:"tenants"`
}

type BackendKindUnion struct {
	DurableObject  *DoBackend             `json:"durableObject,omitempty"`
	ServiceBinding *ServiceBindingBackend `json:"serviceBinding,omitempty"`
	UdsForward     *UdsForwardBackend     `json:"udsForward,omitempty"`
	LeylineNet     *LeylineNetBackend     `json:"leylineNet,omitempty"`
	McpProxy       *HttpForwardBackend    `json:"mcpProxy,omitempty"`
}

type Backend struct {
	Name          string           `json:"name"`
	HandlesPrefix string           `json:"handlesPrefix"`
	Kind          BackendKindUnion `json:"kind"`
}

type DoBackend struct {
	Binding string    `json:"binding"`
	KeyArg  string    `json:"keyArg"`
	Tools   []McpTool `json:"tools"`
}

type ServiceBindingBackend struct {
	Binding string    `json:"binding"`
	Tools   []McpTool `json:"tools"`
}

type UdsForwardBackend struct {
	SocketPath string    `json:"socketPath"`
	Tools      []McpTool `json:"tools"`
}

type LeylineNetBackend struct {
	CompanionUrlBinding string    `json:"companionUrlBinding"`
	UpstreamId          string    `json:"upstreamId"`
	Tools               []McpTool `json:"tools"`
}

type HttpForwardBackend struct {
	UrlBinding      string    `json:"urlBinding"`
	Tools           []McpTool `json:"tools"`
	DynamicTools    bool      `json:"dynamicTools"`
	StripPrefix     string    `json:"stripPrefix"`
	RequiresSession bool      `json:"requiresSession"`
	ProtocolMode    string    `json:"protocolMode"`
	ServiceBinding  string    `json:"serviceBinding"`
	Claims          []string  `json:"claims"`
}

type McpTool struct {
	Name            string `json:"name"`
	Description     string `json:"description"`
	InputSchemaJson string `json:"inputSchemaJson"`
}

type TenantDispatchRow struct {
	Name       string `json:"name"`
	Mode       string `json:"mode"`
	MatchValue string `json:"matchValue"`
	Binding    string `json:"binding"`
}

type GatewayMetadata struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

type Actor struct {
	Fingerprint     string `json:"fingerprint"`
	Algorithm       string `json:"algorithm"`
	PubkeyBinding   string `json:"pubkeyBinding"`
	AttestationRepo string `json:"attestationRepo"`
	TunnelEndpoint  string `json:"tunnelEndpoint"`
}

type InterlacePolicy struct {
	MaxCertLifetimeSeconds uint32 `json:"maxCertLifetimeSeconds"`
	RequireInterlock       bool   `json:"requireInterlock"`
	MinAlgorithm           string `json:"minAlgorithm"`
}
